import requests
import json
import random
import string

url_modA = "https://ec-saasukb-e2e-hd.nat.bt.com/CreateCustomerV2/CustomerValidation/CreateCustomerInPE"
url_modC = "https://ec-saasukb-inlife-hd.nat.bt.com/CreateCustomerV2/CustomerValidation/CreateCustomerInPE"
url_MyAcc = "https://api-test1.ee.co.uk//bt-business-auth/v1/service/01000001983/BB/status"


#print(fname, lname)
'''payload_ModA ={
    "SelectedBusinessDetails": {
        "BusinessDetails": None,
        "SelectedCustomerType": "UKC",
        "SelectedBusinessType": "Proprietorship",
        "IsIncorporated": False,
        "IsCharity": False
    },
    "CRNDetails": {
        "CRNumber": "",
        "IsValid": False,
        "SelectedOptionForCRN": "",
        "CompanyName": "",
        "ShowCompanyModule": False,
        "ShowCRNDetails": False,
        "CHRSiteAddress": "https://beta.companieshouse.gov.uk/search?q=",
        "IsCRNManualValidation": False,
        "ErrorMessage": None,
        "ShowErrorMessage": False,
        "HTTPStatusCode": 200
    },
    "AddressDetails": None,
    "BusinessAddress": {
        "ShowAddressSection": True,
        "SelectedAddressConsent": "None",
        "SelectedAddressMarketingConsent": "Not Asked",
        "SelectedAddress": {
            "SubBuildingName": "",
            "UnitNumber": None,
            "BuildingNumber": "22",
            "BuildingName": "",
            "RoadStreet": None,
            "Town": "Aberdeen",
            "County": "Aberdeenshire",
            "Country": None,
            "PostCode": "AB10 1AU",
            "AddressIdentifier": "R20154670566",
            "CreateAddress": False,
            "Selected": True,
            "SingleLineAddress": "ILLICIT STILL THE, 22, Netherkirkgate, Aberdeen, Aberdeenshire, AB10 1AU",
            "ThoroughfareName": "Netherkirkgate",
            "ThoroughfareNumber": None,
            "Locality": "",
            "OtherHelpInfo": "e.g. Floor or room number, the Windsor suite round the corner, etc",
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": "",
            "OrganisationName": "ILLICIT STILL THE",
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "ShowAddressNotShownAbove": True,
        "ShowSelectedAddress": True,
        "AddressNotFound": False,
        "EnteredAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": "AB10 1AU",
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "TypeOfAddress": None,
        "CustomerAddressDipslayName": "Business",
        "OtherBusinessHelpInfo": None
    },
    "TradingTitleDetails": {
        "TradingTitle": None,
        "ShowTradingTitle": True,
        "IsValid": False,
        "ErrorMessage": None,
        "ShowErrorMessage": False,
        "HTTPStatusCode": 200
    },
    "SelectedSoleTraderDetails": {
        "Title": "Mr",
        "FirstName": fname,
        "LastName": lname,
        "CharityName": None,
        "OtherTitle": "None",
        "SoleTraderDisplayName": "Sole Trader",
        "ErrorMessage": None,
        "ShowErrorMessage": False,
        "HTTPStatusCode": 200
    },
    "SubTitleDetails": None,
    "LegalEntityDetails": {
        "EEReference": ""
    },
    "CharityDetails": {
        "HMRC": "",
        "CharityCommissionNumber": "",
        "CharityName": ""
    },
    "InternationalCodesDetails": None,
    "PrimaryContactDetails": {
        "PrimaryContact": {
            "Title": "Mr.",
            "FirstName": fname,
            "LastName": lname,
            "OtherTitle": "None",
            "PreferredContactChannel": "Email",
            "SelectedJobFunction": "ADMIN",
            "SelectedJobTitle": "ADMINISTRATION MANAGER",
            "KeyDecisionMaker": "Y",
            "Profession": "",
            "JobSeniority": None,
            "ConsentToContact": "Not Asked",
            "SelectedAccessibilityStatus": "Not Specified",
            "JobFunctions": None,
            "AccessibilityStatusList": None,
            "PreferredContact": "Email"
        },
        "PhoneContactList": [
            {
                "IsPriority": "True",
                "PhoneType": "Mobile",
                "IsNonUKCountryCode": False,
                "Number": "0753463472",
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "44",
                "ShowPhoneContact": True,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            }
        ],
        "EmailContactList": [
            {
                "IsPriority": "True",
                "EmailAddress": "subbaram.theerthagiri@bt.com",
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": True,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            }
        ],
        "GenericConsentList": [
            {
                "ConsentType": "Email",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Voice",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "SMS",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "AutoPhoneCall",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "Postal",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Profiling",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "DigMktg",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            }
        ],
        "ResellerId": 0
    },
    "AdditionalContactDetails": {
        "PrimaryContact": {
            "Title": "",
            "FirstName": None,
            "LastName": None,
            "OtherTitle": "None",
            "PreferredContactChannel": "Email",
            "SelectedJobFunction": "",
            "SelectedJobTitle": "",
            "KeyDecisionMaker": "Y",
            "Profession": "",
            "JobSeniority": None,
            "ConsentToContact": "Not Asked",
            "SelectedAccessibilityStatus": "Not Specified",
            "JobFunctions": None,
            "AccessibilityStatusList": None,
            "PreferredContact": "Email"
        },
        "PhoneContactList": [
            {
                "IsPriority": "True",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            }
        ],
        "EmailContactList": [
            {
                "IsPriority": "True",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": True,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            }
        ],
        "GenericConsentList": [
            {
                "ConsentType": "Email",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Voice",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "SMS",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "AutoPhoneCall",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "Postal",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Profiling",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "DigMktg",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            }
        ],
        "ResellerId": 0
    },
    "SelectedPersonalPostalAddress": "SameAsBusiness",
    "EUCountries": None,
    "PersonalPostalAddress": {
        "ShowAddressSection": True,
        "SelectedAddressConsent": "None",
        "SelectedAddressMarketingConsent": "Not Asked",
        "SelectedAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "ShowAddressNotShownAbove": False,
        "ShowSelectedAddress": False,
        "AddressNotFound": False,
        "EnteredAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "TypeOfAddress": None,
        "CustomerAddressDipslayName": "Business",
        "OtherBusinessHelpInfo": None
    },
    "SelectedAdditionalPostalAddress": "SameAsBusiness",
    "AdditionalPostalAddress": {
        "ShowAddressSection": True,
        "SelectedAddressConsent": "None",
        "SelectedAddressMarketingConsent": "Not Asked",
        "SelectedAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "ShowAddressNotShownAbove": False,
        "ShowSelectedAddress": False,
        "AddressNotFound": False,
        "EnteredAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "TypeOfAddress": None,
        "CustomerAddressDipslayName": "Business",
        "OtherBusinessHelpInfo": None
    },
    "AdditionalContact": False,
    "LegacyCustomerDetails": {
        "BtbLegacy": "N",
        "CUGID": None,
        "ReqType": None,
        "LeCode": None,
        "ActionTo": None,
        "ContactId": None,
        "LeId": None,
        "Lec": None,
        "RequestType": None,
        "OrderId": None,
        "Contid": None
    },
    "UserData": {
        "VasServiceInstances": None,
        "isVASLegacyAdmin": False,
        "IsVasAdmin": False,
        "ClientStatusField": None,
        "IsOptionCOn": False,
        "VAS_IS_Strategic": None,
        "IsCustomer": False,
        "UserDomain": None,
        "SecretQuestion": None,
        "LandlineNumber": None,
        "MobileNumber": None,
        "BtwCompanyName": None,
        "AlternateEmailAddress": None,
        "MarketingPreferences": None,
        "SecretAnswer": None,
        "IsSecretQuestionPresent": False,
        "IsSecretAnswerPresent": False,
        "LinkedUserNames": None,
        "PrimaryUserID": None,
        "BtcomUserId": None,
        "IsManageRole": False,
        "LoggedInID": None,
        "UserIdentityDomain": None,
        "ContactID": "",
        "MDMCustomerID": None,
        "UserID": "920191895",
        "Password": None,
        "Alias": None,
        "UserType": "ADMIN",
        "UserNamespace": "BTCOM",
        "ResellerID": "1",
        "ServiceProviderName": "BT_RETAIL_BUSINESS",
        "CustomerID": "",
        "FriendlyName": None,
        "CreatedDate": None,
        "LastLogin": None,
        "IsCDEUser": None,
        "SessionID": "qdjixhiysxu4muxh5lcy3tif",
        "AdminPin": None,
        "BillingAccountKey": "",
        "BillingAccountSystem": "",
        "IsAuthenticated": True,
        "IsUserInDnP": False,
        "IconRequest": None,
        "ServiceInstances": None,
        "CustomerStatus": None,
        "AuthMode": "AZURE",
        "Domain": "ec-saasukb-e2e-hd.nat.bt.com",
        "LeCode": None,
        "LeId": None,
        "AgentEIN": "920191895",
        "AgentName": None,
        "IsCustomerStrategic": False,
        "Title": None,
        "FirstName": None,
        "LastName": None,
        "CurrentCUG": None,
        "TelePhoneNo": None,
        "EmailId": None,
        "UserGroups": None,
        "UserRole": None,
        "UserResponsibilities": "BTCPModifyCeaseApproval,ModifyTerminateEContractWF,BB_SOGFAST_Group,OrderSummaryWorkflow,BBREFRESH_EXISTING_TrialGroup,STOPSELL,BTSalesSearch,BB_FTTP_SVR_TrialGroup,BillingToken,SkipHighValidation,Trial_BTCVComplex,AOEndServiceButton,BTLINECHECKCAPABILITY,CV_Express_5_Year_Contract,BB_SogeaAdvancedInstall,BTCOTAgent,BTBMultiSkilled_Agent,BillingDesktopHostApp,BB_Resilience_TrialGroup,RaiseIssueAgainstOrderwf,BT_PilotGroup,BB_ESCALATE-PREPONE_Group,BTDIwf,BT_SOGEALBW_Group,CloudVoice_Express_Test_Trials,BT_SOGEAFTTPConversion,BTWContractAdminwf,SalesAssistantToolWF,WaiveAllCharges_BTCVExpress,BTBSalesAgentInboundSpecialAgent,ManuallyEndContract,EdgeForAD,BT_FTTPEssentialTiers_Group,BB_StartStopTrial_Group,BT_FTTP_WINBACK_FROM_SOGEA,Vel,TriggerLineCheck,BTBCmplntAgent,BTGetNextRole,BTLineCheckCapabilityHostApp,MyDeskHostApp,CustomerQuickInfo,RebuildAssetWF,Delay_Number_Port,BB_CHOP3_HubSecurity_TrialGroup,MandateHighValidation,BillingDesktopHostApp,BBREFRESH_PHASE1_TrialGroup,BB_BBV5_TrialGroup,BB_SOADSL_TrialGroup2,RemovalITELCUGRestriction,KCIPropMgrApp,CreateEContractWF,CVE_ReuseUnusedHandsets,URL-BTB,AOProvideHubReplacement,BT_TrialGroup,20CN_BB_TrialGroup,CMP_BTBDirSPBE,GBEquipmentWorkflow,BT_FTTPLBW_Group,OffersTest,EECC_Contract_Prod_Agent,AmendAssetAddressWF,BBREFRESH_PHASE2_TrialGroup,BB_RebuildOrderwf,BTCVEMARK2,BTBDirwf,BTBCmplntAppliGroup,BTSportBundle_TrialGroup,BBTOFTTPWINBACK_Group,SalesHostApp,SOGEA_WLTO_Trial,Bundles,UKB_MVNO,BB_FTTP_TrialGroup,BTTrialAgentRole,BB_SOGEA_PREMIUM_TrialGroup,WrapUpApp,BTTrainedAgentRole,DashboardAgent responsibility,Address_Validation_Tool,SalesAssistantToolHostApp,SFSL_OrderData_Button,CVE_numberAssociation,CV_Express_ModifyW73CVDectDevices,CVE2CVConversion responsibility,BB_Cabinet_Reporting,Argon_Price_Management,Fibre_VS_Trial,BB_SOADSL_TrialGroup,VasAdminNewPage_TarilGroup,IPAccess_Order_Cancel,T2RIssueOverviewHierarchyView,CV_Express_ModifyW53CVDectDevices,BB_SSR,BTLocalBusinessHubPage,AgentPaymentModeDTMF,BTSport_TrialGroup,IPAcess_Order_Cancel,BTBCmplntwf,BTCloneCustomerWF,BTBAOTAgent,CV_Express_CiscoATA192,BTBServiceAppliGroup,Number_Port_Cancel,UPFRONT_PAY,BTBDirAgent,BrowseBillingDesktopHostApp,VelRecoverNumber,BTLineCheckCapability,NewOrderCreateAssetWF,CloudVoice_W53Trials,Premium_FFM_Engineer,BB_GFAST_Group,BTBLegacy_N,BB_Superfast_80_20_Agent,GB,DefaultTo360ViewerLandingPage,BTUFTAppliGroup,BB_FTTP_Landline_TrialGroup,BTBServiceAgent,BB_FTTP_PREMIUM_TrialGroup,BB_Expedite_Group,BTCOTwf,CloudVoice_ExpressV2_Test_Trial,CV_Express_UK_Unlimited_V2_Test_Trial,BT_StopSellResign_TrialGroup,BTSaleswf,BB_FTTPCVAssociate_Group,CreateCustomerCanvasTrial,AcquisitionsWF,BTVolumeSalesAgent,BB_HotSite_Trial,BTPANWiFiAgent,WaiveHubChargeGroup,BTBInboundRetentionAOTAgent,MultiportONT,BTSalesHubPage,Unbundle,BTSalesAppliGroup,BB_OptPSTNCeasewithFTTP_TrialGroup,DashboardAgent,BB_WaiveDowngradeChrgGroup,BB_WaiveHubDelChargeGroup,StandaloneBBCPE,VELHostApp,BB_SOGEA_Group,BB_CHOP3_Pro_TrialGroup,ULTRA_TrialGroup,BillingEnquiryWF,BTDIAgent,BT_SOGEALBW,BTBCOTextAOTAgent,360DegreeBetaHostApp,BTWiFiAgent,CVE_concurrent_ordering,BTCreateCustomer,MailboxManagementHostApp,FTTP_WLTO_TrialGroup,Force_Cancel,CloudVoiceBPHostApp,BTBL2CServiceRole,Division_Business,BPSSalesManagerAgent,AppDirectHostApp,GOC_RetrieveOrder,FL_ConversionToSogea,BTSPBEAgent,CV_Express_CiscoATA191,GOC_AmendCancel,BB_Firework_TrialGroup,BTBServicewf,BB_WaiveCeaseChrgGroup,BB_BTBSF_TrialGroup,BTWNonRegulatedProductAccess,AOContractDowngrade,CloudVoice_Complex_Test_Trials,AssetMergeforBundlingWF,BB_WaiveHubChargeGroup,PortNudgeToolHostApp,WriteAccessMCT,BTCInboundSaleswf,BTFraudwf,Reasset,CVTest,IssueMtMyDeskHostApp,MultiTaskAppligroup,BTFraudAgent,MarketoCampaignHostApp,BB_ReplaceBusHubGroup,EECC_Contract_Agent,T2R_CHOP3_Trial,BTGSContractAdminwf,360DegreeViewerHostApp,BTBPhonebookAgent,SalesWorkFlow,BB_CHOP3_Hyperfast_TrialGroup,addressSearch,Paps_Online_TrialGroup,BB_CoP_TrialGroup,EvsSalesForceHostApp,BTBServiceAgent_VAS_Sales_Service,CMP_Cmplnt,BB_CHOP2_TrialGroup,UKB_MVNO,Vel",
        "AliasIDs": None,
        "ChannelProfile": None,
        "IsBackOffice": None,
        "SalesEnquiryTelNo": None,
        "DeliveryEnquiryTelNo": None,
        "HasNCPService": False,
        "TermsAndCondition": False,
        "IsAgentOnline": False,
        "IsCreditVetRequired": True,
        "AdminCrmContactKey": None,
        "AdminPinVerified": 0,
        "UserRoleStatus": 0,
        "clientCredentialStatusField": None,
        "IsCUGAdministrator": False,
        "UserfirstName": "",
        "UserlastName": "",
        "Usertitle": "",
        "UseremailAddress": "",
        "crmContactKey": "",
        "cugId": "",
        "OrgID": None,
        "MasterContactId": None,
        "TradingName": "",
        "Action": "provide",
        "ShadowContacts": None,
        "BlockAgentEIN": None,
        "BlockDate": None,
        "ClientIdentityValueWithNoAlias": None,
        "OUC": None,
        "IsContactUpdateRequired": False,
        "IsMarkedForDeletion": False,
        "MailBoxDeletionDate": None,
        "ReasonForDeletion": None,
        "IsLoginDisabled": False,
        "BTDealingChannel": None,
        "IsProfileSuspended": False,
        "IsAdminPinLocked": False,
        "IsRegistrationPending": False,
        "HasContextChanged": False,
        "SourceSystem": None,
        "IconRequestID": "0901e1c8-5381-4432-bd43-a7b795e89814",
        "IconBacMatch": False,
        "IconServiceIdScenarios": False,
        "OrderBehalfOf": None,
        "PostCode": None,
        "IsProfileValidationPending": False,
        "ProfileActivationCode": None,
        "PrimayContactEmailAddress": None,
        "ContentControlCFSId": None,
        "SMSessionID": None,
        "CUGList": None,
        "CDEUserId": None,
        "Category": "",
        "UUID": None,
        "BusinessAppStatus": None,
        "BusinessAppLastLogin": None,
        "BusinessAppVersion": None,
        "BusinessAppOSVersion": None,
        "AppDirectValidBacs": None,
        "IsMerakiServiceAssociated": False,
        "MerakiDescription": None,
        "ClientCredentialType": None,
        "SecretPin": None,
        "IsSecretPinPresent": False,
        "AggregatedCustomerType": None,
        "ClientIdentityStatus": None,
        "ProfileType": None
    },
    "JourneyData": {
        "userProfResp": None,
        "FTTCInstallLaunch": False,
        "FulfillmentOrderNumber": "",
        "Retrievable": "",
        "ConfiguredDomainItems": None,
        "JourneyUrl": None,
        "ContractID": "",
        "IsOneSiebelPlan": False,
        "OpenOrderValidator": {
            "modifyFlag": 0,
            "orderkey": None,
            "orderType": None,
            "customerAgreedDate": None
        },
        "IsOptionCOn": False,
        "ContactID": "",
        "AoojRecordType": "",
        "FudgeFactor": None,
        "FlowType": "",
        "OpenOrderCheck": True,
        "ModifyUrl": "",
        "Journey_Url": "/CreateCustomerV2/CreateCustomer?btbLegacy=N",
        "MDMCustomerID": None,
        "CustomerID": "",
        "SessionID": None,
        "BillingAccountKey": "",
        "CustomerStatus": None,
        "LeCode": None,
        "LeId": "",
        "AgentEIN": "920191895",
        "IsCustomerStrategic": False,
        "IsCreditVetRequired": False,
        "ProvisionInstruction": "",
        "OrderId": "",
        "AssetId": "",
        "ProductName": "",
        "ProductCode": "",
        "SAction": "provide",
        "RequestId": "0901e1c8-5381-4432-bd43-a7b795e89814",
        "RequestDateTime": "01/12/2023 10:06:53",
        "AgentFirstName": "SOGEA EIN",
        "AgentLastName": "shaik",
        "AgentTelephoneNo": "+44 1442 296997",
        "EmailId": "ayesha.shaik@bt.com",
        "UserRole": "BDU",
        "ChannelProfile": "CS Broadband COT",
        "IsBackOffice": "Y",
        "ReferenceOrderNo": None,
        "OrderVersionNo": None,
        "Channel": "Agent",
        "InteractionType": "",
        "InteractionId": "",
        "ReferenceOderNo": "",
        "WorkitemId": "",
        "WorkitemDescription": "",
        "Faultid": "",
        "ThomasSkyEquipment": None,
        "MsoRefID": "",
        "Interactioncontactid": "",
        "RequestType": "NCust",
        "SalesEnquiryTelNo": "0800400400",
        "AgentType": "",
        "DeliveryEnquiryTelNo": "0800777666",
        "BtDealingChannel": "CCC",
        "OpportunityReferenceNo": "",
        "ServiceID": "",
        "SelectServiceID": None,
        "SelectServicePointId": None,
        "ServicePointId": "",
        "ServiceAccountId": "",
        "SiteId": "",
        "NadKey": "",
        "ProductInstanceId": "",
        "ResellerId": "1",
        "CrossSellerId": "",
        "ThresholdValue": None,
        "BtbLegacyFlag": "",
        "NLTag": "",
        "eBilling": "",
        "DirectDebit": "",
        "Title": "",
        "ContactFirstName": "",
        "ContactLastName": "",
        "Owner": "",
        "CugID": None,
        "BillingAgentEIN": "",
        "ContactIntegrationID": "",
        "IsNewJourney": True,
        "CDEAgentSearchType": "",
        "CDEAgentSearchValue": "",
        "customerJourneyData": {
            "custDetail": None,
            "leEntities": None,
            "leDetails": None,
            "address": None
        },
        "creditVet": {
            "countOfCreditvetCalls": 0,
            "lastTotalRiskValue": 0,
            "readyForCreditCheck": False,
            "firstProductConfiguredCreditCheckDone": False,
            "isProceedToActivationCreditCheckDone": False,
            "mcwVetKey": None
        },
        "IsAssociatedBPR": False,
        "IsMovePageloadRequest": False,
        "IsVASAdminAvailable": False,
        "IsNewVASAdmin": False,
        "IsVASAdminConfigured": False,
        "IsVASCDEProfile": True,
        "ServiceInstanceKey": None,
        "ServiceCode": None,
        "OpenZoneSiks": None,
        "BasketdomainData": None,
        "VASAdmindomainData": None,
        "VASAdminExternalDom": None,
        "ProductDefJson": None,
        "ProductDependencyJson": None,
        "IsFromCustomerZone": False,
        "IsOpportunity": False,
        "T2RFaultRefId": "",
        "ReplacementAssetId": "",
        "IsRetrievedOrder": False,
        "SubStatus": "",
        "ProjectRefId": "",
        "BaseLeadDate": "",
        "OrderCreationDate": "01/12/2023 10:06:53",
        "IsAgentCreditVetSameEIN": False,
        "ExistingWorkItemEIN": None,
        "IsAgentCreditCallDone": False,
        "RedirectToNewAmend": True,
        "GroupOrderNumber": None,
        "CanNavigateBack": True,
        "IsLeadTimeCallMade": False,
        "IsGocOCCopiedToBasket": False,
        "IsCOTAgent": True,
        "IsSalesAgent": True,
        "IsDIAgent": True,
        "IsFirstGOCOrder": None,
        "OrderJourneyType": 1,
        "OrderGUID": "b313815c-3410-4f29-9f6b-67c6f3c2965a",
        "IsBundleProduct": False,
        "IsNewCease": False,
        "RedirectToBundleConversion": False,
        "ConvertToBundleSCode": None,
        "BundleAssetId": None,
        "IsLegacyVasAdmin": False,
        "IsnewBBPage": False,
        "AgentDN": "",
        "CreateLECTP": False,
        "AccountManagerEIN": None,
        "VATEvidence": None,
        "ShouldVisitVATValidationPage": False,
        "IsCloudVoiceJourney": False,
        "IsISDNModifyV2": False,
        "IsCreateOrderExecuted": False,
        "IsDIJourney": False,
        "JourneyLineItemData": None,
        "PlanType": "",
        "IsDirAgent": True,
        "CeaseUrl": "",
        "IsNetworkModify": False,
        "IsValidateRetrieveBasketDone": False,
        "IsMobilityModify": False,
        "IsBusinessAppsActivated": False,
        "ProductGroupName": None,
        "ReturnToIncidentRequired": None,
        "UserProfile": None,
        "IsBbLinked_Sogea": False,
        "BbAssetId_Sogea": None,
        "GroupOrderStatus": None,
        "GroupOrderSubStatus": None,
        "SiteContactVisitedModify": False,
        "IsThirdParty": None,
        "IsSogeaToWlrConversion": False,
        "ValidationLevel": "",
        "IsEscalatePreponeLaunch": False,
        "IsServiceManagerAgent": True,
        "IsAllModifyConfigurationDone": False,
        "IsAllModifyBillingDone": False,
        "IsLowtoHighBundleCompConversion": False,
        "IsFLNetworkModify": False,
        "IncompleteConvert": False,
        "IsCarryOverSelectedForBundle": None,
        "IsOfferApplicable": False,
        "IsNewOD": False,
        "HubAssetId": None,
        "NCallId": "",
        "BundleContractTermsInfo": [],
        "IsBTSportRVChangeAgent": False,
        "IsLikeToLikeBudnleMove": False,
        "IsOverlapBundleMove": False,
        "FTTPInstallLaunch": False,
        "IsStandAlone4GAssureJourney": False,
        "TargetBundleInstallationXmlRef": None,
        "IsESWithFTTPNewONT": False,
        "IsFTTPWithNewONT": False,
        "LeName": "",
        "BBToSogeaConversion": False,
        "AccessLineId": None,
        "RMAuthorisation": None,
        "ReplacementreasonCode": None,
        "ExpertSupportCharge": "",
        "NumberOfWiFiDisksAsseted": "",
        "IsAddressUpdated": False,
        "ReplaceXMLRef": None,
        "SATToolDetails": None,
        "IsESRebookAppointmentWarning": False,
        "NoOfDiscsRequestedForReplacement": "",
        "RecommendedDetails": None,
        "CeaseWithRefund": "",
        "RedirectToNewVasBillingPage": False,
        "IsWLRWithdrawnAddress": False,
        "IsNumberTransferOnPC": False,
        "NumberTransferedOnPC": None,
        "ParentCWDAssetId": None,
        "IsSogeaToFTTPConversion": False,
        "EnableAssociatedOrderingKCIs": None,
        "CeaseAssetIdFromT2R": None,
        "PEGAToolDetails": None,
        "RedirectToBundleBuilderPage": False,
        "IsRecommendationValidationDone": False,
        "IsBTWiFiManagerAgent": False,
        "IsFttpWinBackFromSogea": False,
        "IsPSTNToSogeaConversion": False,
        "IsNTTPTerminationType": False,
        "FieldSupplier": None,
        "SFSAppointmentFields": None,
        "IsBTPANWiFiManagerAgent": False,
        "IsBTSportTrialGroupManager": False,
        "DocumentID": "",
        "SelectedORAddress": None,
        "SelectedSogeaLineProductType": None,
        "SkipForFirstOrder": None,
        "WLRWithdrawlForFTTPPriorityExchangeScenarioInfo": [],
        "IsSolusBundleConversion": False,
        "SolusBundleRetainProductPrice": None,
        "SogeaNonServedPremises": False,
        "IsExpertSetupOpen": None,
        "ExpertSetupOrder": None,
        "DirectoryNumber": None,
        "BB1PFMJourney": False,
        "OldAccessTechnology": None
    },
    "Basket": None,
    "LegalEntityResponse": None,
    "ContactDetails": None,
    "SelectedOrganizationName": None,
    "SelectedOrganizationSacCode": None,
    "IsAdditionalContactChecked": False,
    "OrganizationList": None,
    "ModifyType": None,
    "AccountStatus": None,
    "SelectedCustomerRegion": 0,
    "IsCustomerIdentificationScenario": False,
    "IsFromICON": False,
    "IconCreateCustomerSuccessURL": "https://moda.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?2FDF57A3CBC238FA5C9EC3E6DB44E1B0",
    "IconCreateCustomerFailureURL": "https://moda.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?326FA0E0B5195C775C9EC3E6DB44E1B0",
    "HelpDeskIdentifier": "HELPDESK_PORTAL",
    "EUTaxExemptRefNumber": None,
    "IsEUCountrySelected": False,
    "CUGDetails": None,
    "ContactsList": None,
    "IsModelFromSession": False,
    "ChannelName": "Agent",
    "IsCustomerBaseAgent": False,
    "FlagIsStrategicJourneyAllowed": "ON",
    "IsIncorporated": False,
    "IsContactGenericConsent": True,
    "IsConsentRequired": True,
    "RequestMode": None,
    "IsDirectMode": False,
    "ExternalSystem": None,
    "RedirectUrl": None
}'''
'''payload_ModC = {
    "SelectedBusinessDetails": {
        "BusinessDetails": None,
        "SelectedCustomerType": "UKC",
        "SelectedBusinessType": "Proprietorship",
        "IsIncorporated": False,
        "IsCharity": False
    },
    "CRNDetails": {
        "CRNumber": "",
        "IsValid": False,
        "SelectedOptionForCRN": "",
        "CompanyName": "",
        "ShowCompanyModule": False,
        "ShowCRNDetails": False,
        "CHRSiteAddress": "https://beta.companieshouse.gov.uk/search?q=",
        "IsCRNManualValidation": False,
        "ErrorMessage": None,
        "ShowErrorMessage": False,
        "HTTPStatusCode": 200
    },
    "AddressDetails": None,
    "BusinessAddress": {
        "ShowAddressSection": True,
        "SelectedAddressConsent": "None",
        "SelectedAddressMarketingConsent": "Not Asked",
        "SelectedAddress": {
            "SubBuildingName": "",
            "UnitNumber": None,
            "BuildingNumber": "22",
            "BuildingName": "",
            "RoadStreet": None,
            "Town": "Aberdeen",
            "County": "Aberdeenshire",
            "Country": None,
            "PostCode": "AB10 1AU",
            "AddressIdentifier": "R20154670566",
            "CreateAddress": False,
            "Selected": True,
            "SingleLineAddress": "ILLICIT STILL THE, 22, Netherkirkgate, Aberdeen, Aberdeenshire, AB10 1AU",
            "ThoroughfareName": "Netherkirkgate",
            "ThoroughfareNumber": None,
            "Locality": "",
            "OtherHelpInfo": "e.g. Floor or room number, the Windsor suite round the corner, etc",
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": "",
            "OrganisationName": "ILLICIT STILL THE",
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "ShowAddressNotShownAbove": True,
        "ShowSelectedAddress": True,
        "AddressNotFound": False,
        "EnteredAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": "AB10 1AU",
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "TypeOfAddress": None,
        "CustomerAddressDipslayName": "Business",
        "OtherBusinessHelpInfo": None
    },
    "TradingTitleDetails": {
        "TradingTitle": None,
        "ShowTradingTitle": True,
        "IsValid": False,
        "ErrorMessage": None,
        "ShowErrorMessage": False,
        "HTTPStatusCode": 200
    },
    "SelectedSoleTraderDetails": {
        "Title": "Mr",
        "FirstName": fname,
        "LastName": lname,
        "CharityName": None,
        "OtherTitle": "None",
        "SoleTraderDisplayName": "Sole Trader",
        "ErrorMessage": None,
        "ShowErrorMessage": False,
        "HTTPStatusCode": 200
    },
    "SubTitleDetails": None,
    "LegalEntityDetails": {
        "EEReference": ""
    },
    "CharityDetails": {
        "HMRC": "",
        "CharityCommissionNumber": "",
        "CharityName": ""
    },
    "InternationalCodesDetails": None,
    "PrimaryContactDetails": {
        "PrimaryContact": {
            "Title": "Mr.",
            "FirstName": fname,
            "LastName": lname,
            "OtherTitle": "None",
            "PreferredContactChannel": "Email",
            "SelectedJobFunction": "ADMIN",
            "SelectedJobTitle": "ADMINISTRATION MANAGER",
            "KeyDecisionMaker": "Y",
            "Profession": "",
            "JobSeniority": None,
            "ConsentToContact": "Not Asked",
            "SelectedAccessibilityStatus": "Not Specified",
            "JobFunctions": None,
            "AccessibilityStatusList": None,
            "PreferredContact": "Email"
        },
        "PhoneContactList": [
            {
                "IsPriority": "True",
                "PhoneType": "Mobile",
                "IsNonUKCountryCode": False,
                "Number": "0753463472",
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "44",
                "ShowPhoneContact": True,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            }
        ],
        "EmailContactList": [
            {
                "IsPriority": "True",
                "EmailAddress": "subbaram.theerthagiri@bt.com",
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": True,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            }
        ],
        "GenericConsentList": [
            {
                "ConsentType": "Email",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Voice",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "SMS",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "AutoPhoneCall",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "Postal",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Profiling",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "DigMktg",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            }
        ],
        "ResellerId": 0
    },
    "AdditionalContactDetails": {
        "PrimaryContact": {
            "Title": "",
            "FirstName": None,
            "LastName": None,
            "OtherTitle": "None",
            "PreferredContactChannel": "Email",
            "SelectedJobFunction": "",
            "SelectedJobTitle": "",
            "KeyDecisionMaker": "Y",
            "Profession": "",
            "JobSeniority": None,
            "ConsentToContact": "Not Asked",
            "SelectedAccessibilityStatus": "Not Specified",
            "JobFunctions": None,
            "AccessibilityStatusList": None,
            "PreferredContact": "Email"
        },
        "PhoneContactList": [
            {
                "IsPriority": "True",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            },
            {
                "IsPriority": "False",
                "PhoneType": "",
                "IsNonUKCountryCode": False,
                "Number": None,
                "MarketingConsent": "Not Asked",
                "Extension": None,
                "IVRMessage": None,
                "NonUKCountryCode": "0",
                "ShowPhoneContact": False,
                "ErrorMessage": None,
                "consentType": None,
                "PhoneCallConsent": None,
                "SMSConsent": None,
                "AutomatedPhoneCallsConsent": None
            }
        ],
        "EmailContactList": [
            {
                "IsPriority": "True",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": True,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            },
            {
                "IsPriority": "False",
                "EmailAddress": None,
                "MarketingConsent": "Not Asked",
                "ShowEmailContact": False,
                "SuppressAllBTEmails": False,
                "SuppressAllVendorEmails": False,
                "SuppressAll3rdPartyEmails": False,
                "EmailContactKey": None,
                "ErrorMessage": None,
                "Type": None,
                "EmailConsent": None
            }
        ],
        "GenericConsentList": [
            {
                "ConsentType": "Email",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Voice",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "SMS",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "AutoPhoneCall",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "Postal",
                "ConsentValue": "Not Asked",
                "IsRequired": True
            },
            {
                "ConsentType": "Profiling",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            },
            {
                "ConsentType": "DigMktg",
                "ConsentValue": "Not Asked",
                "IsRequired": False
            }
        ],
        "ResellerId": 0
    },
    "SelectedPersonalPostalAddress": "SameAsBusiness",
    "EUCountries": None,
    "PersonalPostalAddress": {
        "ShowAddressSection": True,
        "SelectedAddressConsent": "None",
        "SelectedAddressMarketingConsent": "Not Asked",
        "SelectedAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "ShowAddressNotShownAbove": False,
        "ShowSelectedAddress": False,
        "AddressNotFound": False,
        "EnteredAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "TypeOfAddress": None,
        "CustomerAddressDipslayName": "Business",
        "OtherBusinessHelpInfo": None
    },
    "SelectedAdditionalPostalAddress": "SameAsBusiness",
    "AdditionalPostalAddress": {
        "ShowAddressSection": True,
        "SelectedAddressConsent": "None",
        "SelectedAddressMarketingConsent": "Not Asked",
        "SelectedAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "ShowAddressNotShownAbove": False,
        "ShowSelectedAddress": False,
        "AddressNotFound": False,
        "EnteredAddress": {
            "SubBuildingName": None,
            "UnitNumber": None,
            "BuildingNumber": None,
            "BuildingName": None,
            "RoadStreet": None,
            "Town": None,
            "County": None,
            "Country": None,
            "PostCode": None,
            "AddressIdentifier": None,
            "CreateAddress": False,
            "Selected": False,
            "SingleLineAddress": None,
            "ThoroughfareName": None,
            "ThoroughfareNumber": None,
            "Locality": None,
            "OtherHelpInfo": None,
            "State": None,
            "SubStreet": None,
            "SubLocality": None,
            "CountyStateProvince": None,
            "SubCountyStateProvince": None,
            "POBox": None,
            "InternationalFlag": None,
            "PAFAddressIdentifier": None,
            "SelectedCountryCode": None,
            "DependentThoroughfareName": None,
            "OrganisationName": None,
            "DontKnowPostCode": False,
            "DependentLocality": None,
            "IsManualAddress": False,
            "PostBox": None,
            "NADKey": None
        },
        "TypeOfAddress": None,
        "CustomerAddressDipslayName": "Business",
        "OtherBusinessHelpInfo": None
    },
    "AdditionalContact": False,
    "LegacyCustomerDetails": {
        "BtbLegacy": "N",
        "CUGID": None,
        "ReqType": None,
        "LeCode": None,
        "ActionTo": None,
        "ContactId": None,
        "LeId": None,
        "Lec": None,
        "RequestType": None,
        "OrderId": None,
        "Contid": None
    },
    "UserData": {
        "VasServiceInstances": None,
        "isVASLegacyAdmin": False,
        "IsVasAdmin": False,
        "ClientStatusField": None,
        "IsOptionCOn": False,
        "VAS_IS_Strategic": None,
        "IsCustomer": False,
        "UserDomain": None,
        "SecretQuestion": None,
        "LandlineNumber": None,
        "MobileNumber": None,
        "BtwCompanyName": None,
        "AlternateEmailAddress": None,
        "MarketingPreferences": None,
        "SecretAnswer": None,
        "IsSecretQuestionPresent": False,
        "IsSecretAnswerPresent": False,
        "LinkedUserNames": None,
        "PrimaryUserID": None,
        "BtcomUserId": None,
        "IsManageRole": False,
        "LoggedInID": None,
        "UserIdentityDomain": None,
        "ContactID": "",
        "MDMCustomerID": None,
        "UserID": "920191895",
        "Password": None,
        "Alias": None,
        "UserType": "ADMIN",
        "UserNamespace": "BTCOM",
        "ResellerID": "1",
        "ServiceProviderName": "BT_RETAIL_BUSINESS",
        "CustomerID": "",
        "FriendlyName": None,
        "CreatedDate": None,
        "LastLogin": None,
        "IsCDEUser": None,
        "SessionID": "veoazsbm10qi4hanloonzzu5",
        "AdminPin": None,
        "BillingAccountKey": "",
        "BillingAccountSystem": "",
        "IsAuthenticated": True,
        "IsUserInDnP": False,
        "IconRequest": None,
        "ServiceInstances": None,
        "CustomerStatus": None,
        "AuthMode": "AZURE",
        "Domain": "ec-saasukb-inlife-hd.nat.bt.com",
        "LeCode": None,
        "LeId": None,
        "AgentEIN": "920191895",
        "AgentName": None,
        "IsCustomerStrategic": False,
        "Title": None,
        "FirstName": None,
        "LastName": None,
        "CurrentCUG": None,
        "TelePhoneNo": None,
        "EmailId": None,
        "UserGroups": None,
        "UserRole": None,
        "UserResponsibilities": "BTCPModifyCeaseApproval,ModifyTerminateEContractWF,BB_SOGFAST_Group,OrderSummaryWorkflow,BBREFRESH_EXISTING_TrialGroup,STOPSELL,BTSalesSearch,BB_FTTP_SVR_TrialGroup,BillingToken,SkipHighValidation,Trial_BTCVComplex,AOEndServiceButton,BTLINECHECKCAPABILITY,CV_Express_5_Year_Contract,BB_SogeaAdvancedInstall,BTCOTAgent,BTBMultiSkilled_Agent,BillingDesktopHostApp,BB_Resilience_TrialGroup,RaiseIssueAgainstOrderwf,BT_PilotGroup,BB_ESCALATE-PREPONE_Group,BTDIwf,BT_SOGEALBW_Group,CloudVoice_Express_Test_Trials,BT_SOGEAFTTPConversion,BTWContractAdminwf,SalesAssistantToolWF,WaiveAllCharges_BTCVExpress,BTBSalesAgentInboundSpecialAgent,ManuallyEndContract,EdgeForAD,BT_FTTPEssentialTiers_Group,BB_StartStopTrial_Group,BT_FTTP_WINBACK_FROM_SOGEA,Vel,TriggerLineCheck,BTBCmplntAgent,BTGetNextRole,BTLineCheckCapabilityHostApp,MyDeskHostApp,CustomerQuickInfo,RebuildAssetWF,Delay_Number_Port,BB_CHOP3_HubSecurity_TrialGroup,MandateHighValidation,BillingDesktopHostApp,BBREFRESH_PHASE1_TrialGroup,BB_BBV5_TrialGroup,BB_SOADSL_TrialGroup2,RemovalITELCUGRestriction,KCIPropMgrApp,CreateEContractWF,CVE_ReuseUnusedHandsets,URL-BTB,AOProvideHubReplacement,BT_TrialGroup,20CN_BB_TrialGroup,CMP_BTBDirSPBE,GBEquipmentWorkflow,BT_FTTPLBW_Group,OffersTest,EECC_Contract_Prod_Agent,AmendAssetAddressWF,BBREFRESH_PHASE2_TrialGroup,BB_RebuildOrderwf,BTCVEMARK2,BTBDirwf,BTBCmplntAppliGroup,BTSportBundle_TrialGroup,BBTOFTTPWINBACK_Group,SalesHostApp,SOGEA_WLTO_Trial,Bundles,UKB_MVNO,BB_FTTP_TrialGroup,BTTrialAgentRole,BB_SOGEA_PREMIUM_TrialGroup,WrapUpApp,BTTrainedAgentRole,DashboardAgent responsibility,Address_Validation_Tool,SalesAssistantToolHostApp,SFSL_OrderData_Button,CVE_numberAssociation,CV_Express_ModifyW73CVDectDevices,CVE2CVConversion responsibility,BB_Cabinet_Reporting,Argon_Price_Management,Fibre_VS_Trial,BB_SOADSL_TrialGroup,VasAdminNewPage_TarilGroup,IPAccess_Order_Cancel,T2RIssueOverviewHierarchyView,CV_Express_ModifyW53CVDectDevices,BB_SSR,BTLocalBusinessHubPage,AgentPaymentModeDTMF,BTSport_TrialGroup,IPAcess_Order_Cancel,BTBCmplntwf,BTCloneCustomerWF,BTBAOTAgent,CV_Express_CiscoATA192,BTBServiceAppliGroup,Number_Port_Cancel,UPFRONT_PAY,BTBDirAgent,BrowseBillingDesktopHostApp,VelRecoverNumber,BTLineCheckCapability,NewOrderCreateAssetWF,CloudVoice_W53Trials,Premium_FFM_Engineer,BB_GFAST_Group,BTBLegacy_N,BB_Superfast_80_20_Agent,GB,DefaultTo360ViewerLandingPage,BTUFTAppliGroup,BB_FTTP_Landline_TrialGroup,BTBServiceAgent,BB_FTTP_PREMIUM_TrialGroup,BB_Expedite_Group,BTCOTwf,CloudVoice_ExpressV2_Test_Trial,CV_Express_UK_Unlimited_V2_Test_Trial,BT_StopSellResign_TrialGroup,BTSaleswf,BB_FTTPCVAssociate_Group,CreateCustomerCanvasTrial,AcquisitionsWF,BTVolumeSalesAgent,BB_HotSite_Trial,BTPANWiFiAgent,WaiveHubChargeGroup,BTBInboundRetentionAOTAgent,MultiportONT,BTSalesHubPage,Unbundle,BTSalesAppliGroup,BB_OptPSTNCeasewithFTTP_TrialGroup,DashboardAgent,BB_WaiveDowngradeChrgGroup,BB_WaiveHubDelChargeGroup,StandaloneBBCPE,VELHostApp,BB_SOGEA_Group,BB_CHOP3_Pro_TrialGroup,ULTRA_TrialGroup,BillingEnquiryWF,BTDIAgent,BT_SOGEALBW,BTBCOTextAOTAgent,360DegreeBetaHostApp,BTWiFiAgent,CVE_concurrent_ordering,BTCreateCustomer,MailboxManagementHostApp,FTTP_WLTO_TrialGroup,Force_Cancel,CloudVoiceBPHostApp,BTBL2CServiceRole,Division_Business,BPSSalesManagerAgent,AppDirectHostApp,GOC_RetrieveOrder,FL_ConversionToSogea,BTSPBEAgent,CV_Express_CiscoATA191,GOC_AmendCancel,BB_Firework_TrialGroup,BTBServicewf,BB_WaiveCeaseChrgGroup,BB_BTBSF_TrialGroup,BTWNonRegulatedProductAccess,AOContractDowngrade,CloudVoice_Complex_Test_Trials,AssetMergeforBundlingWF,BB_WaiveHubChargeGroup,PortNudgeToolHostApp,WriteAccessMCT,BTCInboundSaleswf,BTFraudwf,Reasset,CVTest,IssueMtMyDeskHostApp,MultiTaskAppligroup,BTFraudAgent,MarketoCampaignHostApp,BB_ReplaceBusHubGroup,EECC_Contract_Agent,T2R_CHOP3_Trial,BTGSContractAdminwf,360DegreeViewerHostApp,BTBPhonebookAgent,SalesWorkFlow,BB_CHOP3_Hyperfast_TrialGroup,addressSearch,Paps_Online_TrialGroup,BB_CoP_TrialGroup,EvsSalesForceHostApp,BTBServiceAgent_VAS_Sales_Service,CMP_Cmplnt,BB_CHOP2_TrialGroup,UKB_MVNO,Vel",
        "AliasIDs": None,
        "ChannelProfile": None,
        "IsBackOffice": None,
        "SalesEnquiryTelNo": None,
        "DeliveryEnquiryTelNo": None,
        "HasNCPService": False,
        "TermsAndCondition": False,
        "IsAgentOnline": False,
        "IsCreditVetRequired": True,
        "AdminCrmContactKey": None,
        "AdminPinVerified": 0,
        "UserRoleStatus": 0,
        "clientCredentialStatusField": None,
        "IsCUGAdministrator": False,
        "UserfirstName": "",
        "UserlastName": "",
        "Usertitle": "",
        "UseremailAddress": "",
        "crmContactKey": "",
        "cugId": "",
        "OrgID": None,
        "MasterContactId": None,
        "TradingName": "",
        "Action": "provide",
        "ShadowContacts": None,
        "BlockAgentEIN": None,
        "BlockDate": None,
        "ClientIdentityValueWithNoAlias": None,
        "OUC": None,
        "IsContactUpdateRequired": False,
        "IsMarkedForDeletion": False,
        "MailBoxDeletionDate": None,
        "ReasonForDeletion": None,
        "IsLoginDisabled": False,
        "BTDealingChannel": None,
        "IsProfileSuspended": False,
        "IsAdminPinLocked": False,
        "IsRegistrationPending": False,
        "HasContextChanged": False,
        "SourceSystem": None,
        "IconRequestID": "0901e1c8-5381-4432-bd43-a7b795e89814",
        "IconBacMatch": False,
        "IconServiceIdScenarios": False,
        "OrderBehalfOf": None,
        "PostCode": None,
        "IsProfileValidationPending": False,
        "ProfileActivationCode": None,
        "PrimayContactEmailAddress": None,
        "ContentControlCFSId": None,
        "SMSessionID": None,
        "CUGList": None,
        "CDEUserId": None,
        "Category": "",
        "UUID": None,
        "BusinessAppStatus": None,
        "BusinessAppLastLogin": None,
        "BusinessAppVersion": None,
        "BusinessAppOSVersion": None,
        "AppDirectValidBacs": None,
        "IsMerakiServiceAssociated": False,
        "MerakiDescription": None,
        "ClientCredentialType": None,
        "SecretPin": None,
        "IsSecretPinPresent": False,
        "AggregatedCustomerType": None,
        "ClientIdentityStatus": None,
        "ProfileType": None
    },
    "JourneyData": {
        "userProfResp": None,
        "FTTCInstallLaunch": False,
        "FulfillmentOrderNumber": "",
        "Retrievable": "",
        "ConfiguredDomainItems": None,
        "JourneyUrl": None,
        "ContractID": "",
        "IsOneSiebelPlan": False,
        "OpenOrderValidator": {
            "modifyFlag": 0,
            "orderkey": None,
            "orderType": None,
            "customerAgreedDate": None
        },
        "IsOptionCOn": False,
        "ContactID": "",
        "AoojRecordType": "",
        "FudgeFactor": None,
        "FlowType": "",
        "OpenOrderCheck": True,
        "ModifyUrl": "",
        "Journey_Url": "/CreateCustomerV2/CreateCustomer?btbLegacy=N",
        "MDMCustomerID": None,
        "CustomerID": "",
        "SessionID": None,
        "BillingAccountKey": "",
        "CustomerStatus": None,
        "LeCode": "",
        "LeId": "",
        "AgentEIN": "920191895",
        "IsCustomerStrategic": False,
        "IsCreditVetRequired": False,
        "ProvisionInstruction": "",
        "OrderId": "",
        "AssetId": "",
        "ProductName": "",
        "ProductCode": "",
        "SAction": "provide",
        "RequestId": "0901e1c8-5381-4432-bd43-a7b795e89814",
        "RequestDateTime": "01/12/2023 10:06:53",
        "AgentFirstName": "SOGEA EIN",
        "AgentLastName": "shaik",
        "AgentTelephoneNo": "+44 1442 296997",
        "EmailId": "ayesha.shaik@bt.com",
        "UserRole": "BDU",
        "ChannelProfile": "CS Broadband COT",
        "IsBackOffice": "Y",
        "ReferenceOrderNo": None,
        "OrderVersionNo": None,
        "Channel": "Agent",
        "InteractionType": "",
        "InteractionId": "",
        "ReferenceOderNo": "",
        "WorkitemId": "",
        "WorkitemDescription": "",
        "Faultid": "",
        "ThomasSkyEquipment": None,
        "MsoRefID": "",
        "Interactioncontactid": "",
        "RequestType": "NCust",
        "SalesEnquiryTelNo": "0800400400",
        "AgentType": "",
        "DeliveryEnquiryTelNo": "0800777666",
        "BtDealingChannel": "CCC",
        "OpportunityReferenceNo": "",
        "ServiceID": "",
        "SelectServiceID": None,
        "SelectServicePointId": None,
        "ServicePointId": "",
        "ServiceAccountId": "",
        "SiteId": "",
        "NadKey": "",
        "ProductInstanceId": "",
        "ResellerId": "1",
        "CrossSellerId": "",
        "ThresholdValue": None,
        "BtbLegacyFlag": "",
        "NLTag": "",
        "eBilling": "",
        "DirectDebit": "",
        "Title": "",
        "ContactFirstName": "",
        "ContactLastName": "",
        "Owner": "",
        "CugID": "",
        "BillingAgentEIN": "",
        "ContactIntegrationID": "",
        "IsNewJourney": True,
        "CDEAgentSearchType": "",
        "CDEAgentSearchValue": "",
        "customerJourneyData": {
            "custDetail": None,
            "leEntities": None,
            "leDetails": None,
            "address": None
        },
        "creditVet": {
            "countOfCreditvetCalls": 0,
            "lastTotalRiskValue": 0,
            "readyForCreditCheck": False,
            "firstProductConfiguredCreditCheckDone": False,
            "isProceedToActivationCreditCheckDone": False,
            "mcwVetKey": None
        },
        "IsAssociatedBPR": False,
        "IsMovePageloadRequest": False,
        "IsVASAdminAvailable": False,
        "IsNewVASAdmin": False,
        "IsVASAdminConfigured": False,
        "IsVASCDEProfile": True,
        "ServiceInstanceKey": None,
        "ServiceCode": None,
        "OpenZoneSiks": None,
        "BasketdomainData": None,
        "VASAdmindomainData": None,
        "VASAdminExternalDom": None,
        "ProductDefJson": None,
        "ProductDependencyJson": None,
        "IsFromCustomerZone": False,
        "IsOpportunity": False,
        "T2RFaultRefId": "",
        "ReplacementAssetId": "",
        "IsRetrievedOrder": False,
        "SubStatus": "",
        "ProjectRefId": "",
        "BaseLeadDate": "",
        "OrderCreationDate": "01/12/2023 10:06:53",
        "IsAgentCreditVetSameEIN": False,
        "ExistingWorkItemEIN": None,
        "IsAgentCreditCallDone": False,
        "RedirectToNewAmend": True,
        "GroupOrderNumber": None,
        "CanNavigateBack": True,
        "IsLeadTimeCallMade": False,
        "IsGocOCCopiedToBasket": False,
        "IsCOTAgent": True,
        "IsSalesAgent": True,
        "IsDIAgent": True,
        "IsFirstGOCOrder": None,
        "OrderJourneyType": 1,
        "OrderGUID": "385e2a6d-70a0-4562-a465-221f9ba62f38",
        "IsBundleProduct": False,
        "IsNewCease": False,
        "RedirectToBundleConversion": False,
        "ConvertToBundleSCode": None,
        "BundleAssetId": None,
        "IsLegacyVasAdmin": False,
        "IsnewBBPage": False,
        "AgentDN": "",
        "CreateLECTP": False,
        "AccountManagerEIN": None,
        "VATEvidence": None,
        "ShouldVisitVATValidationPage": False,
        "IsCloudVoiceJourney": False,
        "IsISDNModifyV2": False,
        "IsCreateOrderExecuted": False,
        "IsDIJourney": False,
        "JourneyLineItemData": None,
        "PlanType": "",
        "IsDirAgent": True,
        "CeaseUrl": "",
        "IsNetworkModify": False,
        "IsValidateRetrieveBasketDone": False,
        "IsMobilityModify": False,
        "IsBusinessAppsActivated": False,
        "ProductGroupName": None,
        "ReturnToIncidentRequired": None,
        "UserProfile": None,
        "IsBbLinked_Sogea": False,
        "BbAssetId_Sogea": None,
        "GroupOrderStatus": None,
        "GroupOrderSubStatus": None,
        "SiteContactVisitedModify": False,
        "IsThirdParty": None,
        "IsSogeaToWlrConversion": False,
        "ValidationLevel": "",
        "IsEscalatePreponeLaunch": False,
        "IsServiceManagerAgent": True,
        "IsAllModifyConfigurationDone": False,
        "IsAllModifyBillingDone": False,
        "IsLowtoHighBundleCompConversion": False,
        "IsFLNetworkModify": False,
        "IncompleteConvert": False,
        "IsCarryOverSelectedForBundle": None,
        "IsOfferApplicable": False,
        "IsNewOD": False,
        "HubAssetId": None,
        "NCallId": "",
        "BundleContractTermsInfo": [],
        "IsBTSportRVChangeAgent": False,
        "IsLikeToLikeBudnleMove": False,
        "IsOverlapBundleMove": False,
        "FTTPInstallLaunch": False,
        "IsStandAlone4GAssureJourney": False,
        "TargetBundleInstallationXmlRef": None,
        "IsESWithFTTPNewONT": False,
        "IsFTTPWithNewONT": False,
        "LeName": "",
        "BBToSogeaConversion": False,
        "AccessLineId": None,
        "RMAuthorisation": None,
        "ReplacementreasonCode": None,
        "ExpertSupportCharge": "",
        "NumberOfWiFiDisksAsseted": "",
        "IsAddressUpdated": False,
        "ReplaceXMLRef": None,
        "SATToolDetails": None,
        "IsESRebookAppointmentWarning": False,
        "NoOfDiscsRequestedForReplacement": "",
        "RecommendedDetails": None,
        "CeaseWithRefund": "",
        "RedirectToNewVasBillingPage": False,
        "IsWLRWithdrawnAddress": False,
        "IsNumberTransferOnPC": False,
        "NumberTransferedOnPC": None,
        "ParentCWDAssetId": None,
        "IsSogeaToFTTPConversion": False,
        "EnableAssociatedOrderingKCIs": None,
        "CeaseAssetIdFromT2R": None,
        "PEGAToolDetails": None,
        "RedirectToBundleBuilderPage": False,
        "IsRecommendationValidationDone": False,
        "IsBTWiFiManagerAgent": False,
        "IsFttpWinBackFromSogea": False,
        "IsPSTNToSogeaConversion": False,
        "IsNTTPTerminationType": False,
        "FieldSupplier": None,
        "SFSAppointmentFields": None,
        "IsBTPANWiFiManagerAgent": False,
        "IsBTSportTrialGroupManager": False,
        "DocumentID": "",
        "SelectedORAddress": None,
        "SelectedSogeaLineProductType": None,
        "SkipForFirstOrder": None,
        "WLRWithdrawlForFTTPPriorityExchangeScenarioInfo": [],
        "IsSolusBundleConversion": False,
        "SolusBundleRetainProductPrice": None,
        "SogeaNonServedPremises": False,
        "IsExpertSetupOpen": None,
        "ExpertSetupOrder": None,
        "DirectoryNumber": None,
        "BB1PFMJourney": False,
        "OldAccessTechnology": None
    },
    "Basket": None,
    "LegalEntityResponse": None,
    "ContactDetails": None,
    "SelectedOrganizationName": None,
    "SelectedOrganizationSacCode": None,
    "IsAdditionalContactChecked": False,
    "OrganizationList": None,
    "ModifyType": None,
    "AccountStatus": None,
    "SelectedCustomerRegion": 0,
    "IsCustomerIdentificationScenario": False,
    "IsFromICON": False,
    "IconCreateCustomerSuccessURL": "https://modc.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?2FDF57A3CBC238FA5C9EC3E6DB44E1B0",
    "IconCreateCustomerFailureURL": "https://modc.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?326FA0E0B5195C775C9EC3E6DB44E1B0",
    "HelpDeskIdentifier": "HELPDESK_PORTAL",
    "EUTaxExemptRefNumber": None,
    "IsEUCountrySelected": False,
    "CUGDetails": None,
    "ContactsList": None,
    "IsModelFromSession": False,
    "ChannelName": "Agent",
    "IsCustomerBaseAgent": False,
    "FlagIsStrategicJourneyAllowed": "ON",
    "IsIncorporated": False,
    "IsContactGenericConsent": True,
    "IsConsentRequired": True,
    "RequestMode": None,
    "IsDirectMode": False,
    "ExternalSystem": None,
    "RedirectUrl": None
}'''

#payload_str_ModA = json.dumps(payload_ModA)    # json payload convert into string
#payload_str_ModC = json.dumps(payload_ModC)

jira_api_key = "MDkwNTkxMTA3NDA0OhJKRt7XRrtvpYb0KWUbwRMOw5LZ"
token = "eyJhbGciOiJSUzI1NiIsImtpZCI6InY5TjczZzA1bEY4RlJkWXpCNG4zSm1laHRMUnZyZERDWG84ZEc0VXM1QmMiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJjMjBiYjdiMi1kY2FmLTRlYTQtOTI3Mi1mMDY3ZDQ4YTFhZWEiLCJpc3MiOiJodHRwczovL2Rldi1hdXRoLmJ0LmNvbS8xNTg2NjAzMi0yZmI1LTRlMDAtODg5ZS00OWFhNGU1Y2ZlOGEvdjIuMC8iLCJleHAiOjE3MzY1MDM2MzAsIm5iZiI6MTczNjUwMTgzMCwiY29ycmVsYXRpb25JZCI6IjQ5MDViY2E3LTQ3OWItNGEyYy05NmNiLWEzMzkxYzAxMTE4MCIsImVtYWlsIjoic3JpbnVoZXJlQGJ0LmNvbSIsInN1YiI6IjkwY2ExMTkzLWY5M2UtNDcyNi1hNzcxLWQzZWQwZDhjMWFjOCIsInV1aWQiOiI0YTJmMTBkZi1mZjBiLTEwM2MtYWExMC1iNjg4ZGVmY2FjMDEiLCJ0ZnAiOiJCMkNfMUFfUlBCVF9TaWduSW4iLCJzY3AiOiJkaWdpdGFsLXJlcGFpci12MS5wcmVjaGVja3Mud3JpdGUgZGlnaXRhbC1yZXBhaXItdjEucHJlY2hlY2tzLnJlYWQgYm1zYmlsbGluZ2FjY291bnRzLXYxLmdldGFjY291bnRkZXRhaWxzLnJlYWQgbXlidC5teWFjY291bnQtdjEuYWxsIGJ0Lm15YWNjb3VudC12MS51c2VyLWRldGFpbHMucmVhZCIsImF6cCI6ImQ3NzkxNzQyLWIxMmMtNDNlOS1iYzY2LTM4ZDc4NTc3ODZmZiIsInZlciI6IjEuMCIsImlhdCI6MTczNjUwMTgzMH0.lseJeTfEhEpYekimhIA3zot-r2e4VEiNcLW8ww5Coaolxl6reZhyU2yo4jNmJajtP1vLRia22IZlK-UOf5rE81IrnZJGTFVvpFIZYcsNa_-bmEZ-nPorw-j23MOKQL-cyQUG2FtAFIRxAsqXcHcqu8PTFFalyMyef8q6yOm5hX1OaXaT1_GS9fNVp4MqEAhwt5xXyEpPVurV8bqln9HYM0koYgfJmJGp_nd-pmCaa5tnAyguW52uw1dV22xJDkA6RgIyEefpm68e8THuWIckDOhslDOJGKpskUrid3IDBLf457mc9SM52T3WSOWL_JMNbsMm_p7piIFWzRj_l-97rw"
authKey = "ff8a8c4e270de6d2"
headers = {
    "Accept": "application/json",
    "Content-Type": "application/json",
    "Authorization": "Bearer " + jira_api_key,

}
headers1 = {
    'APIGW-Tracking-Header': '1234',
    'Authorization': 'Bearer ' + token,
    '_authkey': authKey,
    'apigw-client-id': '10cbbbb7-eb4d-42c8-a61d-b79e19ba3e07',
    'apigw-tracking-header': 'cd522af9-f626-4762-893e-e8c8f0e62d13'
}
#proxies = {'https': 'http://cloudproxy.nat.bt.com:8080'}


response = requests.request("GET", url_MyAcc, headers=headers1)
#respose = requests.request("POST", url_modC, data=payload_str_ModC, headers=headers, verify= False)
print(response.text)
#print(pos)


#requests.request("GET", url= "https//amazon.com", data=paload, headers=header, )


