
describe("API testing", function(){
    it("My API test", function(){
        const jira_api_key = "MDkwNTkxMTA3NDA0OhJKRt7XRrtvpYb0KWUbwRMOw5LZ"
        const proxies = {'https': 'http://cloudproxy.nat.bt.com:8080'}

        const fname = 'subbaram'
        const lname = 'theerthagiri'

        const body = {
            "SelectedBusinessDetails": {
                "BusinessDetails": null,
                "SelectedCustomerType": "UKC",
                "SelectedBusinessType": "Proprietorship",
                "IsIncorporated": false,
                "IsCharity": false
            },
            "CRNDetails": {
                "CRNumber": "",
                "IsValid": false,
                "SelectedOptionForCRN": "",
                "CompanyName": "",
                "ShowCompanyModule": false,
                "ShowCRNDetails": false,
                "CHRSiteAddress": "https://beta.companieshouse.gov.uk/search?q=",
                "IsCRNManualValidation": false,
                "ErrorMessage": null,
                "ShowErrorMessage": false,
                "HTTPStatusCode": 200
            },
            "AddressDetails": null,
            "BusinessAddress": {
                "ShowAddressSection": true,
                "SelectedAddressConsent": "null",
                "SelectedAddressMarketingConsent": "Not Asked",
                "SelectedAddress": {
                    "SubBuildingName": "",
                    "UnitNumber": null,
                    "BuildingNumber": "22",
                    "BuildingName": "",
                    "RoadStreet": null,
                    "Town": "Aberdeen",
                    "County": "Aberdeenshire",
                    "Country": null,
                    "PostCode": "AB10 1AU",
                    "AddressIdentifier": "R20154670566",
                    "CreateAddress": false,
                    "Selected": true,
                    "SingleLineAddress": "ILLICIT STILL THE, 22, Netherkirkgate, Aberdeen, Aberdeenshire, AB10 1AU",
                    "ThoroughfareName": "Netherkirkgate",
                    "ThoroughfareNumber": null,
                    "Locality": "",
                    "OtherHelpInfo": "e.g. Floor or room number, the Windsor suite round the corner, etc",
                    "State": null,
                    "SubStreet": null,
                    "SubLocality": null,
                    "CountyStateProvince": null,
                    "SubCountyStateProvince": null,
                    "POBox": null,
                    "InternationalFlag": null,
                    "PAFAddressIdentifier": null,
                    "SelectedCountryCode": null,
                    "DependentThoroughfareName": "",
                    "OrganisationName": "ILLICIT STILL THE",
                    "DontKnowPostCode": false,
                    "DependentLocality": null,
                    "IsManualAddress": false,
                    "PostBox": null,
                    "NADKey": null
                },
                "ShowAddressNotShownAbove": true,
                "ShowSelectedAddress": true,
                "AddressNotFound": false,
                "EnteredAddress": {
                    "SubBuildingName": null,
                    "UnitNumber": null,
                    "BuildingNumber": null,
                    "BuildingName": null,
                    "RoadStreet": null,
                    "Town": null,
                    "County": null,
                    "Country": null,
                    "PostCode": "AB10 1AU",
                    "AddressIdentifier": null,
                    "CreateAddress": false,
                    "Selected": false,
                    "SingleLineAddress": null,
                    "ThoroughfareName": null,
                    "ThoroughfareNumber": null,
                    "Locality": null,
                    "OtherHelpInfo": null,
                    "State": null,
                    "SubStreet": null,
                    "SubLocality": null,
                    "CountyStateProvince": null,
                    "SubCountyStateProvince": null,
                    "POBox": null,
                    "InternationalFlag": null,
                    "PAFAddressIdentifier": null,
                    "SelectedCountryCode": null,
                    "DependentThoroughfareName": null,
                    "OrganisationName": null,
                    "DontKnowPostCode": false,
                    "DependentLocality": null,
                    "IsManualAddress": false,
                    "PostBox": null,
                    "NADKey": null
                },
                "TypeOfAddress": null,
                "CustomerAddressDipslayName": "Business",
                "OtherBusinessHelpInfo": null
            },
            "TradingTitleDetails": {
                "TradingTitle": null,
                "ShowTradingTitle": true,
                "IsValid": false,
                "ErrorMessage": null,
                "ShowErrorMessage": false,
                "HTTPStatusCode": 200
            },
            "SelectedSoleTraderDetails": {
                "Title": "Mr",
                "FirstName": fname,
                "LastName": lname,
                "CharityName": null,
                "OtherTitle": "null",
                "SoleTraderDisplayName": "Sole Trader",
                "ErrorMessage": null,
                "ShowErrorMessage": false,
                "HTTPStatusCode": 200
            },
            "SubTitleDetails": null,
            "LegalEntityDetails": {
                "EEReference": ""
            },
            "CharityDetails": {
                "HMRC": "",
                "CharityCommissionNumber": "",
                "CharityName": ""
            },
            "InternationalCodesDetails": null,
            "PrimaryContactDetails": {
                "PrimaryContact": {
                    "Title": "Mr.",
                    "FirstName": fname,
                    "LastName": lname,
                    "OtherTitle": "null",
                    "PreferredContactChannel": "Email",
                    "SelectedJobFunction": "ADMIN",
                    "SelectedJobTitle": "ADMINISTRATION MANAGER",
                    "KeyDecisionMaker": "Y",
                    "Profession": "",
                    "JobSeniority": null,
                    "ConsentToContact": "Not Asked",
                    "SelectedAccessibilityStatus": "Not Specified",
                    "JobFunctions": null,
                    "AccessibilityStatusList": null,
                    "PreferredContact": "Email"
                },
                "PhoneContactList": [
                    {
                        "IsPriority": "true",
                        "PhoneType": "Mobile",
                        "IsNonUKCountryCode": false,
                        "Number": "0753463472",
                        "MarketingConsent": "Not Asked",
                        "Extension": null,
                        "IVRMessage": null,
                        "NonUKCountryCode": "44",
                        "ShowPhoneContact": true,
                        "ErrorMessage": null,
                        "consentType": null,
                        "PhoneCallConsent": null,
                        "SMSConsent": null,
                        "AutomatedPhoneCallsConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "PhoneType": "",
                        "IsNonUKCountryCode": false,
                        "Number": null,
                        "MarketingConsent": "Not Asked",
                        "Extension": null,
                        "IVRMessage": null,
                        "NonUKCountryCode": "0",
                        "ShowPhoneContact": false,
                        "ErrorMessage": null,
                        "consentType": null,
                        "PhoneCallConsent": null,
                        "SMSConsent": null,
                        "AutomatedPhoneCallsConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "PhoneType": "",
                        "IsNonUKCountryCode": false,
                        "Number": null,
                        "MarketingConsent": "Not Asked",
                        "Extension": null,
                        "IVRMessage": null,
                        "NonUKCountryCode": "0",
                        "ShowPhoneContact": false,
                        "ErrorMessage": null,
                        "consentType": null,
                        "PhoneCallConsent": null,
                        "SMSConsent": null,
                        "AutomatedPhoneCallsConsent": null
                    }
                ],
                "EmailContactList": [
                    {
                        "IsPriority": "true",
                        "EmailAddress": "subbaram.theerthagiri@bt.com",
                        "MarketingConsent": "Not Asked",
                        "ShowEmailContact": true,
                        "SuppressAllBTEmails": false,
                        "SuppressAllVendorEmails": false,
                        "SuppressAll3rdPartyEmails": false,
                        "EmailContactKey": null,
                        "ErrorMessage": null,
                        "Type": null,
                        "EmailConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "EmailAddress": null,
                        "MarketingConsent": "Not Asked",
                        "ShowEmailContact": false,
                        "SuppressAllBTEmails": false,
                        "SuppressAllVendorEmails": false,
                        "SuppressAll3rdPartyEmails": false,
                        "EmailContactKey": null,
                        "ErrorMessage": null,
                        "Type": null,
                        "EmailConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "EmailAddress": null,
                        "MarketingConsent": "Not Asked",
                        "ShowEmailContact": false,
                        "SuppressAllBTEmails": false,
                        "SuppressAllVendorEmails": false,
                        "SuppressAll3rdPartyEmails": false,
                        "EmailContactKey": null,
                        "ErrorMessage": null,
                        "Type": null,
                        "EmailConsent": null
                    }
                ],
                "GenericConsentList": [
                    {
                        "ConsentType": "Email",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "Voice",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "SMS",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "AutoPhoneCall",
                        "ConsentValue": "Not Asked",
                        "IsRequired": false
                    },
                    {
                        "ConsentType": "Postal",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "Profiling",
                        "ConsentValue": "Not Asked",
                        "IsRequired": false
                    },
                    {
                        "ConsentType": "DigMktg",
                        "ConsentValue": "Not Asked",
                        "IsRequired": false
                    }
                ],
                "ResellerId": 0
            },
            "AdditionalContactDetails": {
                "PrimaryContact": {
                    "Title": "",
                    "FirstName": null,
                    "LastName": null,
                    "OtherTitle": "null",
                    "PreferredContactChannel": "Email",
                    "SelectedJobFunction": "",
                    "SelectedJobTitle": "",
                    "KeyDecisionMaker": "Y",
                    "Profession": "",
                    "JobSeniority": null,
                    "ConsentToContact": "Not Asked",
                    "SelectedAccessibilityStatus": "Not Specified",
                    "JobFunctions": null,
                    "AccessibilityStatusList": null,
                    "PreferredContact": "Email"
                },
                "PhoneContactList": [
                    {
                        "IsPriority": "true",
                        "PhoneType": "",
                        "IsNonUKCountryCode": false,
                        "Number": null,
                        "MarketingConsent": "Not Asked",
                        "Extension": null,
                        "IVRMessage": null,
                        "NonUKCountryCode": "0",
                        "ShowPhoneContact": false,
                        "ErrorMessage": null,
                        "consentType": null,
                        "PhoneCallConsent": null,
                        "SMSConsent": null,
                        "AutomatedPhoneCallsConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "PhoneType": "",
                        "IsNonUKCountryCode": false,
                        "Number": null,
                        "MarketingConsent": "Not Asked",
                        "Extension": null,
                        "IVRMessage": null,
                        "NonUKCountryCode": "0",
                        "ShowPhoneContact": false,
                        "ErrorMessage": null,
                        "consentType": null,
                        "PhoneCallConsent": null,
                        "SMSConsent": null,
                        "AutomatedPhoneCallsConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "PhoneType": "",
                        "IsNonUKCountryCode": false,
                        "Number": null,
                        "MarketingConsent": "Not Asked",
                        "Extension": null,
                        "IVRMessage": null,
                        "NonUKCountryCode": "0",
                        "ShowPhoneContact": false,
                        "ErrorMessage": null,
                        "consentType": null,
                        "PhoneCallConsent": null,
                        "SMSConsent": null,
                        "AutomatedPhoneCallsConsent": null
                    }
                ],
                "EmailContactList": [
                    {
                        "IsPriority": "true",
                        "EmailAddress": null,
                        "MarketingConsent": "Not Asked",
                        "ShowEmailContact": true,
                        "SuppressAllBTEmails": false,
                        "SuppressAllVendorEmails": false,
                        "SuppressAll3rdPartyEmails": false,
                        "EmailContactKey": null,
                        "ErrorMessage": null,
                        "Type": null,
                        "EmailConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "EmailAddress": null,
                        "MarketingConsent": "Not Asked",
                        "ShowEmailContact": false,
                        "SuppressAllBTEmails": false,
                        "SuppressAllVendorEmails": false,
                        "SuppressAll3rdPartyEmails": false,
                        "EmailContactKey": null,
                        "ErrorMessage": null,
                        "Type": null,
                        "EmailConsent": null
                    },
                    {
                        "IsPriority": "false",
                        "EmailAddress": null,
                        "MarketingConsent": "Not Asked",
                        "ShowEmailContact": false,
                        "SuppressAllBTEmails": false,
                        "SuppressAllVendorEmails": false,
                        "SuppressAll3rdPartyEmails": false,
                        "EmailContactKey": null,
                        "ErrorMessage": null,
                        "Type": null,
                        "EmailConsent": null
                    }
                ],
                "GenericConsentList": [
                    {
                        "ConsentType": "Email",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "Voice",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "SMS",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "AutoPhoneCall",
                        "ConsentValue": "Not Asked",
                        "IsRequired": false
                    },
                    {
                        "ConsentType": "Postal",
                        "ConsentValue": "Not Asked",
                        "IsRequired": true
                    },
                    {
                        "ConsentType": "Profiling",
                        "ConsentValue": "Not Asked",
                        "IsRequired": false
                    },
                    {
                        "ConsentType": "DigMktg",
                        "ConsentValue": "Not Asked",
                        "IsRequired": false
                    }
                ],
                "ResellerId": 0
            },
            "SelectedPersonalPostalAddress": "SameAsBusiness",
            "EUCountries": null,
            "PersonalPostalAddress": {
                "ShowAddressSection": true,
                "SelectedAddressConsent": "null",
                "SelectedAddressMarketingConsent": "Not Asked",
                "SelectedAddress": {
                    "SubBuildingName": null,
                    "UnitNumber": null,
                    "BuildingNumber": null,
                    "BuildingName": null,
                    "RoadStreet": null,
                    "Town": null,
                    "County": null,
                    "Country": null,
                    "PostCode": null,
                    "AddressIdentifier": null,
                    "CreateAddress": false,
                    "Selected": false,
                    "SingleLineAddress": null,
                    "ThoroughfareName": null,
                    "ThoroughfareNumber": null,
                    "Locality": null,
                    "OtherHelpInfo": null,
                    "State": null,
                    "SubStreet": null,
                    "SubLocality": null,
                    "CountyStateProvince": null,
                    "SubCountyStateProvince": null,
                    "POBox": null,
                    "InternationalFlag": null,
                    "PAFAddressIdentifier": null,
                    "SelectedCountryCode": null,
                    "DependentThoroughfareName": null,
                    "OrganisationName": null,
                    "DontKnowPostCode": false,
                    "DependentLocality": null,
                    "IsManualAddress": false,
                    "PostBox": null,
                    "NADKey": null
                },
                "ShowAddressNotShownAbove": false,
                "ShowSelectedAddress": false,
                "AddressNotFound": false,
                "EnteredAddress": {
                    "SubBuildingName": null,
                    "UnitNumber": null,
                    "BuildingNumber": null,
                    "BuildingName": null,
                    "RoadStreet": null,
                    "Town": null,
                    "County": null,
                    "Country": null,
                    "PostCode": null,
                    "AddressIdentifier": null,
                    "CreateAddress": false,
                    "Selected": false,
                    "SingleLineAddress": null,
                    "ThoroughfareName": null,
                    "ThoroughfareNumber": null,
                    "Locality": null,
                    "OtherHelpInfo": null,
                    "State": null,
                    "SubStreet": null,
                    "SubLocality": null,
                    "CountyStateProvince": null,
                    "SubCountyStateProvince": null,
                    "POBox": null,
                    "InternationalFlag": null,
                    "PAFAddressIdentifier": null,
                    "SelectedCountryCode": null,
                    "DependentThoroughfareName": null,
                    "OrganisationName": null,
                    "DontKnowPostCode": false,
                    "DependentLocality": null,
                    "IsManualAddress": false,
                    "PostBox": null,
                    "NADKey": null
                },
                "TypeOfAddress": null,
                "CustomerAddressDipslayName": "Business",
                "OtherBusinessHelpInfo": null
            },
            "SelectedAdditionalPostalAddress": "SameAsBusiness",
            "AdditionalPostalAddress": {
                "ShowAddressSection": true,
                "SelectedAddressConsent": "null",
                "SelectedAddressMarketingConsent": "Not Asked",
                "SelectedAddress": {
                    "SubBuildingName": null,
                    "UnitNumber": null,
                    "BuildingNumber": null,
                    "BuildingName": null,
                    "RoadStreet": null,
                    "Town": null,
                    "County": null,
                    "Country": null,
                    "PostCode": null,
                    "AddressIdentifier": null,
                    "CreateAddress": false,
                    "Selected": false,
                    "SingleLineAddress": null,
                    "ThoroughfareName": null,
                    "ThoroughfareNumber": null,
                    "Locality": null,
                    "OtherHelpInfo": null,
                    "State": null,
                    "SubStreet": null,
                    "SubLocality": null,
                    "CountyStateProvince": null,
                    "SubCountyStateProvince": null,
                    "POBox": null,
                    "InternationalFlag": null,
                    "PAFAddressIdentifier": null,
                    "SelectedCountryCode": null,
                    "DependentThoroughfareName": null,
                    "OrganisationName": null,
                    "DontKnowPostCode": false,
                    "DependentLocality": null,
                    "IsManualAddress": false,
                    "PostBox": null,
                    "NADKey": null
                },
                "ShowAddressNotShownAbove": false,
                "ShowSelectedAddress": false,
                "AddressNotFound": false,
                "EnteredAddress": {
                    "SubBuildingName": null,
                    "UnitNumber": null,
                    "BuildingNumber": null,
                    "BuildingName": null,
                    "RoadStreet": null,
                    "Town": null,
                    "County": null,
                    "Country": null,
                    "PostCode": null,
                    "AddressIdentifier": null,
                    "CreateAddress": false,
                    "Selected": false,
                    "SingleLineAddress": null,
                    "ThoroughfareName": null,
                    "ThoroughfareNumber": null,
                    "Locality": null,
                    "OtherHelpInfo": null,
                    "State": null,
                    "SubStreet": null,
                    "SubLocality": null,
                    "CountyStateProvince": null,
                    "SubCountyStateProvince": null,
                    "POBox": null,
                    "InternationalFlag": null,
                    "PAFAddressIdentifier": null,
                    "SelectedCountryCode": null,
                    "DependentThoroughfareName": null,
                    "OrganisationName": null,
                    "DontKnowPostCode": false,
                    "DependentLocality": null,
                    "IsManualAddress": false,
                    "PostBox": null,
                    "NADKey": null
                },
                "TypeOfAddress": null,
                "CustomerAddressDipslayName": "Business",
                "OtherBusinessHelpInfo": null
            },
            "AdditionalContact": false,
            "LegacyCustomerDetails": {
                "BtbLegacy": "N",
                "CUGID": null,
                "ReqType": null,
                "LeCode": null,
                "ActionTo": null,
                "ContactId": null,
                "LeId": null,
                "Lec": null,
                "RequestType": null,
                "OrderId": null,
                "Contid": null
            },
            "UserData": {
                "VasServiceInstances": null,
                "isVASLegacyAdmin": false,
                "IsVasAdmin": false,
                "ClientStatusField": null,
                "IsOptionCOn": false,
                "VAS_IS_Strategic": null,
                "IsCustomer": false,
                "UserDomain": null,
                "SecretQuestion": null,
                "LandlineNumber": null,
                "MobileNumber": null,
                "BtwCompanyName": null,
                "AlternateEmailAddress": null,
                "MarketingPreferences": null,
                "SecretAnswer": null,
                "IsSecretQuestionPresent": false,
                "IsSecretAnswerPresent": false,
                "LinkedUserNames": null,
                "PrimaryUserID": null,
                "BtcomUserId": null,
                "IsManageRole": false,
                "LoggedInID": null,
                "UserIdentityDomain": null,
                "ContactID": "",
                "MDMCustomerID": null,
                "UserID": "920191895",
                "Password": null,
                "Alias": null,
                "UserType": "ADMIN",
                "UserNamespace": "BTCOM",
                "ResellerID": "1",
                "ServiceProviderName": "BT_RETAIL_BUSINESS",
                "CustomerID": "",
                "FriendlyName": null,
                "CreatedDate": null,
                "LastLogin": null,
                "IsCDEUser": null,
                "SessionID": "qdjixhiysxu4muxh5lcy3tif",
                "AdminPin": null,
                "BillingAccountKey": "",
                "BillingAccountSystem": "",
                "IsAuthenticated": true,
                "IsUserInDnP": false,
                "IconRequest": null,
                "ServiceInstances": null,
                "CustomerStatus": null,
                "AuthMode": "AZURE",
                "Domain": "ec-saasukb-e2e-hd.nat.bt.com",
                "LeCode": null,
                "LeId": null,
                "AgentEIN": "920191895",
                "AgentName": null,
                "IsCustomerStrategic": false,
                "Title": null,
                "FirstName": null,
                "LastName": null,
                "CurrentCUG": null,
                "TelePhoneNo": null,
                "EmailId": null,
                "UserGroups": null,
                "UserRole": null,
                "UserResponsibilities": "BTCPModifyCeaseApproval,ModifyTerminateEContractWF,BB_SOGFAST_Group,OrderSummaryWorkflow,BBREFRESH_EXISTING_TrialGroup,STOPSELL,BTSalesSearch,BB_FTTP_SVR_TrialGroup,BillingToken,SkipHighValidation,Trial_BTCVComplex,AOEndServiceButton,BTLINECHECKCAPABILITY,CV_Express_5_Year_Contract,BB_SogeaAdvancedInstall,BTCOTAgent,BTBMultiSkilled_Agent,BillingDesktopHostApp,BB_Resilience_TrialGroup,RaiseIssueAgainstOrderwf,BT_PilotGroup,BB_ESCALATE-PREPONE_Group,BTDIwf,BT_SOGEALBW_Group,CloudVoice_Express_Test_Trials,BT_SOGEAFTTPConversion,BTWContractAdminwf,SalesAssistantToolWF,WaiveAllCharges_BTCVExpress,BTBSalesAgentInboundSpecialAgent,ManuallyEndContract,EdgeForAD,BT_FTTPEssentialTiers_Group,BB_StartStopTrial_Group,BT_FTTP_WINBACK_FROM_SOGEA,Vel,TriggerLineCheck,BTBCmplntAgent,BTGetNextRole,BTLineCheckCapabilityHostApp,MyDeskHostApp,CustomerQuickInfo,RebuildAssetWF,Delay_Number_Port,BB_CHOP3_HubSecurity_TrialGroup,MandateHighValidation,BillingDesktopHostApp,BBREFRESH_PHASE1_TrialGroup,BB_BBV5_TrialGroup,BB_SOADSL_TrialGroup2,RemovalITELCUGRestriction,KCIPropMgrApp,CreateEContractWF,CVE_ReuseUnusedHandsets,URL-BTB,AOProvideHubReplacement,BT_TrialGroup,20CN_BB_TrialGroup,CMP_BTBDirSPBE,GBEquipmentWorkflow,BT_FTTPLBW_Group,OffersTest,EECC_Contract_Prod_Agent,AmendAssetAddressWF,BBREFRESH_PHASE2_TrialGroup,BB_RebuildOrderwf,BTCVEMARK2,BTBDirwf,BTBCmplntAppliGroup,BTSportBundle_TrialGroup,BBTOFTTPWINBACK_Group,SalesHostApp,SOGEA_WLTO_Trial,Bundles,UKB_MVNO,BB_FTTP_TrialGroup,BTTrialAgentRole,BB_SOGEA_PREMIUM_TrialGroup,WrapUpApp,BTTrainedAgentRole,DashboardAgent responsibility,Address_Validation_Tool,SalesAssistantToolHostApp,SFSL_OrderData_Button,CVE_numberAssociation,CV_Express_ModifyW73CVDectDevices,CVE2CVConversion responsibility,BB_Cabinet_Reporting,Argon_Price_Management,Fibre_VS_Trial,BB_SOADSL_TrialGroup,VasAdminNewPage_TarilGroup,IPAccess_Order_Cancel,T2RIssueOverviewHierarchyView,CV_Express_ModifyW53CVDectDevices,BB_SSR,BTLocalBusinessHubPage,AgentPaymentModeDTMF,BTSport_TrialGroup,IPAcess_Order_Cancel,BTBCmplntwf,BTCloneCustomerWF,BTBAOTAgent,CV_Express_CiscoATA192,BTBServiceAppliGroup,Number_Port_Cancel,UPFRONT_PAY,BTBDirAgent,BrowseBillingDesktopHostApp,VelRecoverNumber,BTLineCheckCapability,NewOrderCreateAssetWF,CloudVoice_W53Trials,Premium_FFM_Engineer,BB_GFAST_Group,BTBLegacy_N,BB_Superfast_80_20_Agent,GB,DefaultTo360ViewerLandingPage,BTUFTAppliGroup,BB_FTTP_Landline_TrialGroup,BTBServiceAgent,BB_FTTP_PREMIUM_TrialGroup,BB_Expedite_Group,BTCOTwf,CloudVoice_ExpressV2_Test_Trial,CV_Express_UK_Unlimited_V2_Test_Trial,BT_StopSellResign_TrialGroup,BTSaleswf,BB_FTTPCVAssociate_Group,CreateCustomerCanvasTrial,AcquisitionsWF,BTVolumeSalesAgent,BB_HotSite_Trial,BTPANWiFiAgent,WaiveHubChargeGroup,BTBInboundRetentionAOTAgent,MultiportONT,BTSalesHubPage,Unbundle,BTSalesAppliGroup,BB_OptPSTNCeasewithFTTP_TrialGroup,DashboardAgent,BB_WaiveDowngradeChrgGroup,BB_WaiveHubDelChargeGroup,StandaloneBBCPE,VELHostApp,BB_SOGEA_Group,BB_CHOP3_Pro_TrialGroup,ULTRA_TrialGroup,BillingEnquiryWF,BTDIAgent,BT_SOGEALBW,BTBCOTextAOTAgent,360DegreeBetaHostApp,BTWiFiAgent,CVE_concurrent_ordering,BTCreateCustomer,MailboxManagementHostApp,FTTP_WLTO_TrialGroup,Force_Cancel,CloudVoiceBPHostApp,BTBL2CServiceRole,Division_Business,BPSSalesManagerAgent,AppDirectHostApp,GOC_RetrieveOrder,FL_ConversionToSogea,BTSPBEAgent,CV_Express_CiscoATA191,GOC_AmendCancel,BB_Firework_TrialGroup,BTBServicewf,BB_WaiveCeaseChrgGroup,BB_BTBSF_TrialGroup,BTWNonRegulatedProductAccess,AOContractDowngrade,CloudVoice_Complex_Test_Trials,AssetMergeforBundlingWF,BB_WaiveHubChargeGroup,PortNudgeToolHostApp,WriteAccessMCT,BTCInboundSaleswf,BTFraudwf,Reasset,CVTest,IssueMtMyDeskHostApp,MultiTaskAppligroup,BTFraudAgent,MarketoCampaignHostApp,BB_ReplaceBusHubGroup,EECC_Contract_Agent,T2R_CHOP3_Trial,BTGSContractAdminwf,360DegreeViewerHostApp,BTBPhonebookAgent,SalesWorkFlow,BB_CHOP3_Hyperfast_TrialGroup,addressSearch,Paps_Online_TrialGroup,BB_CoP_TrialGroup,EvsSalesForceHostApp,BTBServiceAgent_VAS_Sales_Service,CMP_Cmplnt,BB_CHOP2_TrialGroup,UKB_MVNO,Vel",
                "AliasIDs": null,
                "ChannelProfile": null,
                "IsBackOffice": null,
                "SalesEnquiryTelNo": null,
                "DeliveryEnquiryTelNo": null,
                "HasNCPService": false,
                "TermsAndCondition": false,
                "IsAgentOnline": false,
                "IsCreditVetRequired": true,
                "AdminCrmContactKey": null,
                "AdminPinVerified": 0,
                "UserRoleStatus": 0,
                "clientCredentialStatusField": null,
                "IsCUGAdministrator": false,
                "UserfirstName": "",
                "UserlastName": "",
                "Usertitle": "",
                "UseremailAddress": "",
                "crmContactKey": "",
                "cugId": "",
                "OrgID": null,
                "MasterContactId": null,
                "TradingName": "",
                "Action": "provide",
                "ShadowContacts": null,
                "BlockAgentEIN": null,
                "BlockDate": null,
                "ClientIdentityValueWithNoAlias": null,
                "OUC": null,
                "IsContactUpdateRequired": false,
                "IsMarkedForDeletion": false,
                "MailBoxDeletionDate": null,
                "ReasonForDeletion": null,
                "IsLoginDisabled": false,
                "BTDealingChannel": null,
                "IsProfileSuspended": false,
                "IsAdminPinLocked": false,
                "IsRegistrationPending": false,
                "HasContextChanged": false,
                "SourceSystem": null,
                "IconRequestID": "0901e1c8-5381-4432-bd43-a7b795e89814",
                "IconBacMatch": false,
                "IconServiceIdScenarios": false,
                "OrderBehalfOf": null,
                "PostCode": null,
                "IsProfileValidationPending": false,
                "ProfileActivationCode": null,
                "PrimayContactEmailAddress": null,
                "ContentControlCFSId": null,
                "SMSessionID": null,
                "CUGList": null,
                "CDEUserId": null,
                "Category": "",
                "UUID": null,
                "BusinessAppStatus": null,
                "BusinessAppLastLogin": null,
                "BusinessAppVersion": null,
                "BusinessAppOSVersion": null,
                "AppDirectValidBacs": null,
                "IsMerakiServiceAssociated": false,
                "MerakiDescription": null,
                "ClientCredentialType": null,
                "SecretPin": null,
                "IsSecretPinPresent": false,
                "AggregatedCustomerType": null,
                "ClientIdentityStatus": null,
                "ProfileType": null
            },
            "JourneyData": {
                "userProfResp": null,
                "FTTCInstallLaunch": false,
                "FulfillmentOrderNumber": "",
                "Retrievable": "",
                "ConfiguredDomainItems": null,
                "JourneyUrl": null,
                "ContractID": "",
                "IsOneSiebelPlan": false,
                "OpenOrderValidator": {
                    "modifyFlag": 0,
                    "orderkey": null,
                    "orderType": null,
                    "customerAgreedDate": null
                },
                "IsOptionCOn": false,
                "ContactID": "",
                "AoojRecordType": "",
                "FudgeFactor": null,
                "FlowType": "",
                "OpenOrderCheck": true,
                "ModifyUrl": "",
                "Journey_Url": "/CreateCustomerV2/CreateCustomer?btbLegacy=N",
                "MDMCustomerID": null,
                "CustomerID": "",
                "SessionID": null,
                "BillingAccountKey": "",
                "CustomerStatus": null,
                "LeCode": null,
                "LeId": "",
                "AgentEIN": "920191895",
                "IsCustomerStrategic": false,
                "IsCreditVetRequired": false,
                "ProvisionInstruction": "",
                "OrderId": "",
                "AssetId": "",
                "ProductName": "",
                "ProductCode": "",
                "SAction": "provide",
                "RequestId": "0901e1c8-5381-4432-bd43-a7b795e89814",
                "RequestDateTime": "01/12/2023 10:06:53",
                "AgentFirstName": "SOGEA EIN",
                "AgentLastName": "shaik",
                "AgentTelephoneNo": "+44 1442 296997",
                "EmailId": "ayesha.shaik@bt.com",
                "UserRole": "BDU",
                "ChannelProfile": "CS Broadband COT",
                "IsBackOffice": "Y",
                "ReferenceOrderNo": null,
                "OrderVersionNo": null,
                "Channel": "Agent",
                "InteractionType": "",
                "InteractionId": "",
                "ReferenceOderNo": "",
                "WorkitemId": "",
                "WorkitemDescription": "",
                "Faultid": "",
                "ThomasSkyEquipment": null,
                "MsoRefID": "",
                "Interactioncontactid": "",
                "RequestType": "NCust",
                "SalesEnquiryTelNo": "0800400400",
                "AgentType": "",
                "DeliveryEnquiryTelNo": "0800777666",
                "BtDealingChannel": "CCC",
                "OpportunityReferenceNo": "",
                "ServiceID": "",
                "SelectServiceID": null,
                "SelectServicePointId": null,
                "ServicePointId": "",
                "ServiceAccountId": "",
                "SiteId": "",
                "NadKey": "",
                "ProductInstanceId": "",
                "ResellerId": "1",
                "CrossSellerId": "",
                "ThresholdValue": null,
                "BtbLegacyFlag": "",
                "NLTag": "",
                "eBilling": "",
                "DirectDebit": "",
                "Title": "",
                "ContactFirstName": "",
                "ContactLastName": "",
                "Owner": "",
                "CugID": null,
                "BillingAgentEIN": "",
                "ContactIntegrationID": "",
                "IsNewJourney": true,
                "CDEAgentSearchType": "",
                "CDEAgentSearchValue": "",
                "customerJourneyData": {
                    "custDetail": null,
                    "leEntities": null,
                    "leDetails": null,
                    "address": null
                },
                "creditVet": {
                    "countOfCreditvetCalls": 0,
                    "lastTotalRiskValue": 0,
                    "readyForCreditCheck": false,
                    "firstProductConfiguredCreditCheckDone": false,
                    "isProceedToActivationCreditCheckDone": false,
                    "mcwVetKey": null
                },
                "IsAssociatedBPR": false,
                "IsMovePageloadRequest": false,
                "IsVASAdminAvailable": false,
                "IsNewVASAdmin": false,
                "IsVASAdminConfigured": false,
                "IsVASCDEProfile": true,
                "ServiceInstanceKey": null,
                "ServiceCode": null,
                "OpenZoneSiks": null,
                "BasketdomainData": null,
                "VASAdmindomainData": null,
                "VASAdminExternalDom": null,
                "ProductDefJson": null,
                "ProductDependencyJson": null,
                "IsFromCustomerZone": false,
                "IsOpportunity": false,
                "T2RFaultRefId": "",
                "ReplacementAssetId": "",
                "IsRetrievedOrder": false,
                "SubStatus": "",
                "ProjectRefId": "",
                "BaseLeadDate": "",
                "OrderCreationDate": "01/12/2023 10:06:53",
                "IsAgentCreditVetSameEIN": false,
                "ExistingWorkItemEIN": null,
                "IsAgentCreditCallDone": false,
                "RedirectToNewAmend": true,
                "GroupOrderNumber": null,
                "CanNavigateBack": true,
                "IsLeadTimeCallMade": false,
                "IsGocOCCopiedToBasket": false,
                "IsCOTAgent": true,
                "IsSalesAgent": true,
                "IsDIAgent": true,
                "IsFirstGOCOrder": null,
                "OrderJourneyType": 1,
                "OrderGUID": "b313815c-3410-4f29-9f6b-67c6f3c2965a",
                "IsBundleProduct": false,
                "IsNewCease": false,
                "RedirectToBundleConversion": false,
                "ConvertToBundleSCode": null,
                "BundleAssetId": null,
                "IsLegacyVasAdmin": false,
                "IsnewBBPage": false,
                "AgentDN": "",
                "CreateLECTP": false,
                "AccountManagerEIN": null,
                "VATEvidence": null,
                "ShouldVisitVATValidationPage": false,
                "IsCloudVoiceJourney": false,
                "IsISDNModifyV2": false,
                "IsCreateOrderExecuted": false,
                "IsDIJourney": false,
                "JourneyLineItemData": null,
                "PlanType": "",
                "IsDirAgent": true,
                "CeaseUrl": "",
                "IsNetworkModify": false,
                "IsValidateRetrieveBasketDone": false,
                "IsMobilityModify": false,
                "IsBusinessAppsActivated": false,
                "ProductGroupName": null,
                "ReturnToIncidentRequired": null,
                "UserProfile": null,
                "IsBbLinked_Sogea": false,
                "BbAssetId_Sogea": null,
                "GroupOrderStatus": null,
                "GroupOrderSubStatus": null,
                "SiteContactVisitedModify": false,
                "IsThirdParty": null,
                "IsSogeaToWlrConversion": false,
                "ValidationLevel": "",
                "IsEscalatePreponeLaunch": false,
                "IsServiceManagerAgent": true,
                "IsAllModifyConfigurationDone": false,
                "IsAllModifyBillingDone": false,
                "IsLowtoHighBundleCompConversion": false,
                "IsFLNetworkModify": false,
                "IncompleteConvert": false,
                "IsCarryOverSelectedForBundle": null,
                "IsOfferApplicable": false,
                "IsNewOD": false,
                "HubAssetId": null,
                "NCallId": "",
                "BundleContractTermsInfo": [],
                "IsBTSportRVChangeAgent": false,
                "IsLikeToLikeBudnleMove": false,
                "IsOverlapBundleMove": false,
                "FTTPInstallLaunch": false,
                "IsStandAlone4GAssureJourney": false,
                "TargetBundleInstallationXmlRef": null,
                "IsESWithFTTPNewONT": false,
                "IsFTTPWithNewONT": false,
                "LeName": "",
                "BBToSogeaConversion": false,
                "AccessLineId": null,
                "RMAuthorisation": null,
                "ReplacementreasonCode": null,
                "ExpertSupportCharge": "",
                "NumberOfWiFiDisksAsseted": "",
                "IsAddressUpdated": false,
                "ReplaceXMLRef": null,
                "SATToolDetails": null,
                "IsESRebookAppointmentWarning": false,
                "NoOfDiscsRequestedForReplacement": "",
                "RecommendedDetails": null,
                "CeaseWithRefund": "",
                "RedirectToNewVasBillingPage": false,
                "IsWLRWithdrawnAddress": false,
                "IsNumberTransferOnPC": false,
                "NumberTransferedOnPC": null,
                "ParentCWDAssetId": null,
                "IsSogeaToFTTPConversion": false,
                "EnableAssociatedOrderingKCIs": null,
                "CeaseAssetIdFromT2R": null,
                "PEGAToolDetails": null,
                "RedirectToBundleBuilderPage": false,
                "IsRecommendationValidationDone": false,
                "IsBTWiFiManagerAgent": false,
                "IsFttpWinBackFromSogea": false,
                "IsPSTNToSogeaConversion": false,
                "IsNTTPTerminationType": false,
                "FieldSupplier": null,
                "SFSAppointmentFields": null,
                "IsBTPANWiFiManagerAgent": false,
                "IsBTSportTrialGroupManager": false,
                "DocumentID": "",
                "SelectedORAddress": null,
                "SelectedSogeaLineProductType": null,
                "SkipForFirstOrder": null,
                "WLRWithdrawlForFTTPPriorityExchangeScenarioInfo": [],
                "IsSolusBundleConversion": false,
                "SolusBundleRetainProductPrice": null,
                "SogeaNonServedPremises": false,
                "IsExpertSetupOpen": null,
                "ExpertSetupOrder": null,
                "DirectoryNumber": null,
                "BB1PFMJourney": false,
                "OldAccessTechnology": null
            },
            "Basket": null,
            "LegalEntityResponse": null,
            "ContactDetails": null,
            "SelectedOrganizationName": null,
            "SelectedOrganizationSacCode": null,
            "IsAdditionalContactChecked": false,
            "OrganizationList": null,
            "ModifyType": null,
            "AccountStatus": null,
            "SelectedCustomerRegion": 0,
            "IsCustomerIdentificationScenario": false,
            "IsFromICON": false,
            "IconCreateCustomerSuccessURL": "https://moda.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?2FDF57A3CBC238FA5C9EC3E6DB44E1B0",
            "IconCreateCustomerFailureURL": "https://moda.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?326FA0E0B5195C775C9EC3E6DB44E1B0",
            "HelpDeskIdentifier": "HELPDESK_PORTAL",
            "EUTaxExemptRefNumber": null,
            "IsEUCountrySelected": false,
            "CUGDetails": null,
            "ContactsList": null,
            "IsModelFromSession": false,
            "ChannelName": "Agent",
            "IsCustomerBaseAgent": false,
            "FlagIsStrategicJourneyAllowed": "ON",
            "IsIncorporated": false,
            "IsContactGenericConsent": true,
            "IsConsentRequired": true,
            "RequestMode": null,
            "IsDirectMode": false,
            "ExternalSystem": null,
            "RedirectUrl": null
        }
        //payload = JSON.dumps(body)
        const payload = JSON.stringify(body);
        cy.request({
            method: 'POST',
            url: 'https://ec-saasukb-e2e-hd.nat.bt.com/CreateCustomerV2/CustomerValidation/CreateCustomerInPE',
            /* body: {
                "SelectedBusinessDetails": {
                    "BusinessDetails": None,
                    "SelectedCustomerType": "UKC",
                    "SelectedBusinessType": "Proprietorship",
                    "IsIncorporated": False,
                    "IsCharity": False
                },
                "CRNDetails": {
                    "CRNumber": "",
                    "IsValid": False,
                    "SelectedOptionForCRN": "",
                    "CompanyName": "",
                    "ShowCompanyModule": False,
                    "ShowCRNDetails": False,
                    "CHRSiteAddress": "https://beta.companieshouse.gov.uk/search?q=",
                    "IsCRNManualValidation": False,
                    "ErrorMessage": None,
                    "ShowErrorMessage": False,
                    "HTTPStatusCode": 200
                },
                "AddressDetails": None,
                "BusinessAddress": {
                    "ShowAddressSection": True,
                    "SelectedAddressConsent": "None",
                    "SelectedAddressMarketingConsent": "Not Asked",
                    "SelectedAddress": {
                        "SubBuildingName": "",
                        "UnitNumber": None,
                        "BuildingNumber": "22",
                        "BuildingName": "",
                        "RoadStreet": None,
                        "Town": "Aberdeen",
                        "County": "Aberdeenshire",
                        "Country": None,
                        "PostCode": "AB10 1AU",
                        "AddressIdentifier": "R20154670566",
                        "CreateAddress": False,
                        "Selected": True,
                        "SingleLineAddress": "ILLICIT STILL THE, 22, Netherkirkgate, Aberdeen, Aberdeenshire, AB10 1AU",
                        "ThoroughfareName": "Netherkirkgate",
                        "ThoroughfareNumber": None,
                        "Locality": "",
                        "OtherHelpInfo": "e.g. Floor or room number, the Windsor suite round the corner, etc",
                        "State": None,
                        "SubStreet": None,
                        "SubLocality": None,
                        "CountyStateProvince": None,
                        "SubCountyStateProvince": None,
                        "POBox": None,
                        "InternationalFlag": None,
                        "PAFAddressIdentifier": None,
                        "SelectedCountryCode": None,
                        "DependentThoroughfareName": "",
                        "OrganisationName": "ILLICIT STILL THE",
                        "DontKnowPostCode": False,
                        "DependentLocality": None,
                        "IsManualAddress": False,
                        "PostBox": None,
                        "NADKey": None
                    },
                    "ShowAddressNotShownAbove": True,
                    "ShowSelectedAddress": True,
                    "AddressNotFound": False,
                    "EnteredAddress": {
                        "SubBuildingName": None,
                        "UnitNumber": None,
                        "BuildingNumber": None,
                        "BuildingName": None,
                        "RoadStreet": None,
                        "Town": None,
                        "County": None,
                        "Country": None,
                        "PostCode": "AB10 1AU",
                        "AddressIdentifier": None,
                        "CreateAddress": False,
                        "Selected": False,
                        "SingleLineAddress": None,
                        "ThoroughfareName": None,
                        "ThoroughfareNumber": None,
                        "Locality": None,
                        "OtherHelpInfo": None,
                        "State": None,
                        "SubStreet": None,
                        "SubLocality": None,
                        "CountyStateProvince": None,
                        "SubCountyStateProvince": None,
                        "POBox": None,
                        "InternationalFlag": None,
                        "PAFAddressIdentifier": None,
                        "SelectedCountryCode": None,
                        "DependentThoroughfareName": None,
                        "OrganisationName": None,
                        "DontKnowPostCode": False,
                        "DependentLocality": None,
                        "IsManualAddress": False,
                        "PostBox": None,
                        "NADKey": None
                    },
                    "TypeOfAddress": None,
                    "CustomerAddressDipslayName": "Business",
                    "OtherBusinessHelpInfo": None
                },
                "TradingTitleDetails": {
                    "TradingTitle": None,
                    "ShowTradingTitle": True,
                    "IsValid": False,
                    "ErrorMessage": None,
                    "ShowErrorMessage": False,
                    "HTTPStatusCode": 200
                },
                "SelectedSoleTraderDetails": {
                    "Title": "Mr",
                    "FirstName": fname,
                    "LastName": lname,
                    "CharityName": None,
                    "OtherTitle": "None",
                    "SoleTraderDisplayName": "Sole Trader",
                    "ErrorMessage": None,
                    "ShowErrorMessage": False,
                    "HTTPStatusCode": 200
                },
                "SubTitleDetails": None,
                "LegalEntityDetails": {
                    "EEReference": ""
                },
                "CharityDetails": {
                    "HMRC": "",
                    "CharityCommissionNumber": "",
                    "CharityName": ""
                },
                "InternationalCodesDetails": None,
                "PrimaryContactDetails": {
                    "PrimaryContact": {
                        "Title": "Mr.",
                        "FirstName": fname,
                        "LastName": lname,
                        "OtherTitle": "None",
                        "PreferredContactChannel": "Email",
                        "SelectedJobFunction": "ADMIN",
                        "SelectedJobTitle": "ADMINISTRATION MANAGER",
                        "KeyDecisionMaker": "Y",
                        "Profession": "",
                        "JobSeniority": None,
                        "ConsentToContact": "Not Asked",
                        "SelectedAccessibilityStatus": "Not Specified",
                        "JobFunctions": None,
                        "AccessibilityStatusList": None,
                        "PreferredContact": "Email"
                    },
                    "PhoneContactList": [
                        {
                            "IsPriority": "True",
                            "PhoneType": "Mobile",
                            "IsNonUKCountryCode": False,
                            "Number": "0753463472",
                            "MarketingConsent": "Not Asked",
                            "Extension": None,
                            "IVRMessage": None,
                            "NonUKCountryCode": "44",
                            "ShowPhoneContact": True,
                            "ErrorMessage": None,
                            "consentType": None,
                            "PhoneCallConsent": None,
                            "SMSConsent": None,
                            "AutomatedPhoneCallsConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "PhoneType": "",
                            "IsNonUKCountryCode": False,
                            "Number": None,
                            "MarketingConsent": "Not Asked",
                            "Extension": None,
                            "IVRMessage": None,
                            "NonUKCountryCode": "0",
                            "ShowPhoneContact": False,
                            "ErrorMessage": None,
                            "consentType": None,
                            "PhoneCallConsent": None,
                            "SMSConsent": None,
                            "AutomatedPhoneCallsConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "PhoneType": "",
                            "IsNonUKCountryCode": False,
                            "Number": None,
                            "MarketingConsent": "Not Asked",
                            "Extension": None,
                            "IVRMessage": None,
                            "NonUKCountryCode": "0",
                            "ShowPhoneContact": False,
                            "ErrorMessage": None,
                            "consentType": None,
                            "PhoneCallConsent": None,
                            "SMSConsent": None,
                            "AutomatedPhoneCallsConsent": None
                        }
                    ],
                    "EmailContactList": [
                        {
                            "IsPriority": "True",
                            "EmailAddress": "subbaram.theerthagiri@bt.com",
                            "MarketingConsent": "Not Asked",
                            "ShowEmailContact": True,
                            "SuppressAllBTEmails": False,
                            "SuppressAllVendorEmails": False,
                            "SuppressAll3rdPartyEmails": False,
                            "EmailContactKey": None,
                            "ErrorMessage": None,
                            "Type": None,
                            "EmailConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "EmailAddress": None,
                            "MarketingConsent": "Not Asked",
                            "ShowEmailContact": False,
                            "SuppressAllBTEmails": False,
                            "SuppressAllVendorEmails": False,
                            "SuppressAll3rdPartyEmails": False,
                            "EmailContactKey": None,
                            "ErrorMessage": None,
                            "Type": None,
                            "EmailConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "EmailAddress": None,
                            "MarketingConsent": "Not Asked",
                            "ShowEmailContact": False,
                            "SuppressAllBTEmails": False,
                            "SuppressAllVendorEmails": False,
                            "SuppressAll3rdPartyEmails": False,
                            "EmailContactKey": None,
                            "ErrorMessage": None,
                            "Type": None,
                            "EmailConsent": None
                        }
                    ],
                    "GenericConsentList": [
                        {
                            "ConsentType": "Email",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "Voice",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "SMS",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "AutoPhoneCall",
                            "ConsentValue": "Not Asked",
                            "IsRequired": False
                        },
                        {
                            "ConsentType": "Postal",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "Profiling",
                            "ConsentValue": "Not Asked",
                            "IsRequired": False
                        },
                        {
                            "ConsentType": "DigMktg",
                            "ConsentValue": "Not Asked",
                            "IsRequired": False
                        }
                    ],
                    "ResellerId": 0
                },
                "AdditionalContactDetails": {
                    "PrimaryContact": {
                        "Title": "",
                        "FirstName": None,
                        "LastName": None,
                        "OtherTitle": "None",
                        "PreferredContactChannel": "Email",
                        "SelectedJobFunction": "",
                        "SelectedJobTitle": "",
                        "KeyDecisionMaker": "Y",
                        "Profession": "",
                        "JobSeniority": None,
                        "ConsentToContact": "Not Asked",
                        "SelectedAccessibilityStatus": "Not Specified",
                        "JobFunctions": None,
                        "AccessibilityStatusList": None,
                        "PreferredContact": "Email"
                    },
                    "PhoneContactList": [
                        {
                            "IsPriority": "True",
                            "PhoneType": "",
                            "IsNonUKCountryCode": False,
                            "Number": None,
                            "MarketingConsent": "Not Asked",
                            "Extension": None,
                            "IVRMessage": None,
                            "NonUKCountryCode": "0",
                            "ShowPhoneContact": False,
                            "ErrorMessage": None,
                            "consentType": None,
                            "PhoneCallConsent": None,
                            "SMSConsent": None,
                            "AutomatedPhoneCallsConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "PhoneType": "",
                            "IsNonUKCountryCode": False,
                            "Number": None,
                            "MarketingConsent": "Not Asked",
                            "Extension": None,
                            "IVRMessage": None,
                            "NonUKCountryCode": "0",
                            "ShowPhoneContact": False,
                            "ErrorMessage": None,
                            "consentType": None,
                            "PhoneCallConsent": None,
                            "SMSConsent": None,
                            "AutomatedPhoneCallsConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "PhoneType": "",
                            "IsNonUKCountryCode": False,
                            "Number": None,
                            "MarketingConsent": "Not Asked",
                            "Extension": None,
                            "IVRMessage": None,
                            "NonUKCountryCode": "0",
                            "ShowPhoneContact": False,
                            "ErrorMessage": None,
                            "consentType": None,
                            "PhoneCallConsent": None,
                            "SMSConsent": None,
                            "AutomatedPhoneCallsConsent": None
                        }
                    ],
                    "EmailContactList": [
                        {
                            "IsPriority": "True",
                            "EmailAddress": None,
                            "MarketingConsent": "Not Asked",
                            "ShowEmailContact": True,
                            "SuppressAllBTEmails": False,
                            "SuppressAllVendorEmails": False,
                            "SuppressAll3rdPartyEmails": False,
                            "EmailContactKey": None,
                            "ErrorMessage": None,
                            "Type": None,
                            "EmailConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "EmailAddress": None,
                            "MarketingConsent": "Not Asked",
                            "ShowEmailContact": False,
                            "SuppressAllBTEmails": False,
                            "SuppressAllVendorEmails": False,
                            "SuppressAll3rdPartyEmails": False,
                            "EmailContactKey": None,
                            "ErrorMessage": None,
                            "Type": None,
                            "EmailConsent": None
                        },
                        {
                            "IsPriority": "False",
                            "EmailAddress": None,
                            "MarketingConsent": "Not Asked",
                            "ShowEmailContact": False,
                            "SuppressAllBTEmails": False,
                            "SuppressAllVendorEmails": False,
                            "SuppressAll3rdPartyEmails": False,
                            "EmailContactKey": None,
                            "ErrorMessage": None,
                            "Type": None,
                            "EmailConsent": None
                        }
                    ],
                    "GenericConsentList": [
                        {
                            "ConsentType": "Email",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "Voice",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "SMS",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "AutoPhoneCall",
                            "ConsentValue": "Not Asked",
                            "IsRequired": False
                        },
                        {
                            "ConsentType": "Postal",
                            "ConsentValue": "Not Asked",
                            "IsRequired": True
                        },
                        {
                            "ConsentType": "Profiling",
                            "ConsentValue": "Not Asked",
                            "IsRequired": False
                        },
                        {
                            "ConsentType": "DigMktg",
                            "ConsentValue": "Not Asked",
                            "IsRequired": False
                        }
                    ],
                    "ResellerId": 0
                },
                "SelectedPersonalPostalAddress": "SameAsBusiness",
                "EUCountries": None,
                "PersonalPostalAddress": {
                    "ShowAddressSection": True,
                    "SelectedAddressConsent": "None",
                    "SelectedAddressMarketingConsent": "Not Asked",
                    "SelectedAddress": {
                        "SubBuildingName": None,
                        "UnitNumber": None,
                        "BuildingNumber": None,
                        "BuildingName": None,
                        "RoadStreet": None,
                        "Town": None,
                        "County": None,
                        "Country": None,
                        "PostCode": None,
                        "AddressIdentifier": None,
                        "CreateAddress": False,
                        "Selected": False,
                        "SingleLineAddress": None,
                        "ThoroughfareName": None,
                        "ThoroughfareNumber": None,
                        "Locality": None,
                        "OtherHelpInfo": None,
                        "State": None,
                        "SubStreet": None,
                        "SubLocality": None,
                        "CountyStateProvince": None,
                        "SubCountyStateProvince": None,
                        "POBox": None,
                        "InternationalFlag": None,
                        "PAFAddressIdentifier": None,
                        "SelectedCountryCode": None,
                        "DependentThoroughfareName": None,
                        "OrganisationName": None,
                        "DontKnowPostCode": False,
                        "DependentLocality": None,
                        "IsManualAddress": False,
                        "PostBox": None,
                        "NADKey": None
                    },
                    "ShowAddressNotShownAbove": False,
                    "ShowSelectedAddress": False,
                    "AddressNotFound": False,
                    "EnteredAddress": {
                        "SubBuildingName": None,
                        "UnitNumber": None,
                        "BuildingNumber": None,
                        "BuildingName": None,
                        "RoadStreet": None,
                        "Town": None,
                        "County": None,
                        "Country": None,
                        "PostCode": None,
                        "AddressIdentifier": None,
                        "CreateAddress": False,
                        "Selected": False,
                        "SingleLineAddress": None,
                        "ThoroughfareName": None,
                        "ThoroughfareNumber": None,
                        "Locality": None,
                        "OtherHelpInfo": None,
                        "State": None,
                        "SubStreet": None,
                        "SubLocality": None,
                        "CountyStateProvince": None,
                        "SubCountyStateProvince": None,
                        "POBox": None,
                        "InternationalFlag": None,
                        "PAFAddressIdentifier": None,
                        "SelectedCountryCode": None,
                        "DependentThoroughfareName": None,
                        "OrganisationName": None,
                        "DontKnowPostCode": False,
                        "DependentLocality": None,
                        "IsManualAddress": False,
                        "PostBox": None,
                        "NADKey": None
                    },
                    "TypeOfAddress": None,
                    "CustomerAddressDipslayName": "Business",
                    "OtherBusinessHelpInfo": None
                },
                "SelectedAdditionalPostalAddress": "SameAsBusiness",
                "AdditionalPostalAddress": {
                    "ShowAddressSection": True,
                    "SelectedAddressConsent": "None",
                    "SelectedAddressMarketingConsent": "Not Asked",
                    "SelectedAddress": {
                        "SubBuildingName": None,
                        "UnitNumber": None,
                        "BuildingNumber": None,
                        "BuildingName": None,
                        "RoadStreet": None,
                        "Town": None,
                        "County": None,
                        "Country": None,
                        "PostCode": None,
                        "AddressIdentifier": None,
                        "CreateAddress": False,
                        "Selected": False,
                        "SingleLineAddress": None,
                        "ThoroughfareName": None,
                        "ThoroughfareNumber": None,
                        "Locality": None,
                        "OtherHelpInfo": None,
                        "State": None,
                        "SubStreet": None,
                        "SubLocality": None,
                        "CountyStateProvince": None,
                        "SubCountyStateProvince": None,
                        "POBox": None,
                        "InternationalFlag": None,
                        "PAFAddressIdentifier": None,
                        "SelectedCountryCode": None,
                        "DependentThoroughfareName": None,
                        "OrganisationName": None,
                        "DontKnowPostCode": False,
                        "DependentLocality": None,
                        "IsManualAddress": False,
                        "PostBox": None,
                        "NADKey": None
                    },
                    "ShowAddressNotShownAbove": False,
                    "ShowSelectedAddress": False,
                    "AddressNotFound": False,
                    "EnteredAddress": {
                        "SubBuildingName": None,
                        "UnitNumber": None,
                        "BuildingNumber": None,
                        "BuildingName": None,
                        "RoadStreet": None,
                        "Town": None,
                        "County": None,
                        "Country": None,
                        "PostCode": None,
                        "AddressIdentifier": None,
                        "CreateAddress": False,
                        "Selected": False,
                        "SingleLineAddress": None,
                        "ThoroughfareName": None,
                        "ThoroughfareNumber": None,
                        "Locality": None,
                        "OtherHelpInfo": None,
                        "State": None,
                        "SubStreet": None,
                        "SubLocality": None,
                        "CountyStateProvince": None,
                        "SubCountyStateProvince": None,
                        "POBox": None,
                        "InternationalFlag": None,
                        "PAFAddressIdentifier": None,
                        "SelectedCountryCode": None,
                        "DependentThoroughfareName": None,
                        "OrganisationName": None,
                        "DontKnowPostCode": False,
                        "DependentLocality": None,
                        "IsManualAddress": False,
                        "PostBox": None,
                        "NADKey": None
                    },
                    "TypeOfAddress": None,
                    "CustomerAddressDipslayName": "Business",
                    "OtherBusinessHelpInfo": None
                },
                "AdditionalContact": False,
                "LegacyCustomerDetails": {
                    "BtbLegacy": "N",
                    "CUGID": None,
                    "ReqType": None,
                    "LeCode": None,
                    "ActionTo": None,
                    "ContactId": None,
                    "LeId": None,
                    "Lec": None,
                    "RequestType": None,
                    "OrderId": None,
                    "Contid": None
                },
                "UserData": {
                    "VasServiceInstances": None,
                    "isVASLegacyAdmin": False,
                    "IsVasAdmin": False,
                    "ClientStatusField": None,
                    "IsOptionCOn": False,
                    "VAS_IS_Strategic": None,
                    "IsCustomer": False,
                    "UserDomain": None,
                    "SecretQuestion": None,
                    "LandlineNumber": None,
                    "MobileNumber": None,
                    "BtwCompanyName": None,
                    "AlternateEmailAddress": None,
                    "MarketingPreferences": None,
                    "SecretAnswer": None,
                    "IsSecretQuestionPresent": False,
                    "IsSecretAnswerPresent": False,
                    "LinkedUserNames": None,
                    "PrimaryUserID": None,
                    "BtcomUserId": None,
                    "IsManageRole": False,
                    "LoggedInID": None,
                    "UserIdentityDomain": None,
                    "ContactID": "",
                    "MDMCustomerID": None,
                    "UserID": "920191895",
                    "Password": None,
                    "Alias": None,
                    "UserType": "ADMIN",
                    "UserNamespace": "BTCOM",
                    "ResellerID": "1",
                    "ServiceProviderName": "BT_RETAIL_BUSINESS",
                    "CustomerID": "",
                    "FriendlyName": None,
                    "CreatedDate": None,
                    "LastLogin": None,
                    "IsCDEUser": None,
                    "SessionID": "qdjixhiysxu4muxh5lcy3tif",
                    "AdminPin": None,
                    "BillingAccountKey": "",
                    "BillingAccountSystem": "",
                    "IsAuthenticated": True,
                    "IsUserInDnP": False,
                    "IconRequest": None,
                    "ServiceInstances": None,
                    "CustomerStatus": None,
                    "AuthMode": "AZURE",
                    "Domain": "ec-saasukb-e2e-hd.nat.bt.com",
                    "LeCode": None,
                    "LeId": None,
                    "AgentEIN": "920191895",
                    "AgentName": None,
                    "IsCustomerStrategic": False,
                    "Title": None,
                    "FirstName": None,
                    "LastName": None,
                    "CurrentCUG": None,
                    "TelePhoneNo": None,
                    "EmailId": None,
                    "UserGroups": None,
                    "UserRole": None,
                    "UserResponsibilities": "BTCPModifyCeaseApproval,ModifyTerminateEContractWF,BB_SOGFAST_Group,OrderSummaryWorkflow,BBREFRESH_EXISTING_TrialGroup,STOPSELL,BTSalesSearch,BB_FTTP_SVR_TrialGroup,BillingToken,SkipHighValidation,Trial_BTCVComplex,AOEndServiceButton,BTLINECHECKCAPABILITY,CV_Express_5_Year_Contract,BB_SogeaAdvancedInstall,BTCOTAgent,BTBMultiSkilled_Agent,BillingDesktopHostApp,BB_Resilience_TrialGroup,RaiseIssueAgainstOrderwf,BT_PilotGroup,BB_ESCALATE-PREPONE_Group,BTDIwf,BT_SOGEALBW_Group,CloudVoice_Express_Test_Trials,BT_SOGEAFTTPConversion,BTWContractAdminwf,SalesAssistantToolWF,WaiveAllCharges_BTCVExpress,BTBSalesAgentInboundSpecialAgent,ManuallyEndContract,EdgeForAD,BT_FTTPEssentialTiers_Group,BB_StartStopTrial_Group,BT_FTTP_WINBACK_FROM_SOGEA,Vel,TriggerLineCheck,BTBCmplntAgent,BTGetNextRole,BTLineCheckCapabilityHostApp,MyDeskHostApp,CustomerQuickInfo,RebuildAssetWF,Delay_Number_Port,BB_CHOP3_HubSecurity_TrialGroup,MandateHighValidation,BillingDesktopHostApp,BBREFRESH_PHASE1_TrialGroup,BB_BBV5_TrialGroup,BB_SOADSL_TrialGroup2,RemovalITELCUGRestriction,KCIPropMgrApp,CreateEContractWF,CVE_ReuseUnusedHandsets,URL-BTB,AOProvideHubReplacement,BT_TrialGroup,20CN_BB_TrialGroup,CMP_BTBDirSPBE,GBEquipmentWorkflow,BT_FTTPLBW_Group,OffersTest,EECC_Contract_Prod_Agent,AmendAssetAddressWF,BBREFRESH_PHASE2_TrialGroup,BB_RebuildOrderwf,BTCVEMARK2,BTBDirwf,BTBCmplntAppliGroup,BTSportBundle_TrialGroup,BBTOFTTPWINBACK_Group,SalesHostApp,SOGEA_WLTO_Trial,Bundles,UKB_MVNO,BB_FTTP_TrialGroup,BTTrialAgentRole,BB_SOGEA_PREMIUM_TrialGroup,WrapUpApp,BTTrainedAgentRole,DashboardAgent responsibility,Address_Validation_Tool,SalesAssistantToolHostApp,SFSL_OrderData_Button,CVE_numberAssociation,CV_Express_ModifyW73CVDectDevices,CVE2CVConversion responsibility,BB_Cabinet_Reporting,Argon_Price_Management,Fibre_VS_Trial,BB_SOADSL_TrialGroup,VasAdminNewPage_TarilGroup,IPAccess_Order_Cancel,T2RIssueOverviewHierarchyView,CV_Express_ModifyW53CVDectDevices,BB_SSR,BTLocalBusinessHubPage,AgentPaymentModeDTMF,BTSport_TrialGroup,IPAcess_Order_Cancel,BTBCmplntwf,BTCloneCustomerWF,BTBAOTAgent,CV_Express_CiscoATA192,BTBServiceAppliGroup,Number_Port_Cancel,UPFRONT_PAY,BTBDirAgent,BrowseBillingDesktopHostApp,VelRecoverNumber,BTLineCheckCapability,NewOrderCreateAssetWF,CloudVoice_W53Trials,Premium_FFM_Engineer,BB_GFAST_Group,BTBLegacy_N,BB_Superfast_80_20_Agent,GB,DefaultTo360ViewerLandingPage,BTUFTAppliGroup,BB_FTTP_Landline_TrialGroup,BTBServiceAgent,BB_FTTP_PREMIUM_TrialGroup,BB_Expedite_Group,BTCOTwf,CloudVoice_ExpressV2_Test_Trial,CV_Express_UK_Unlimited_V2_Test_Trial,BT_StopSellResign_TrialGroup,BTSaleswf,BB_FTTPCVAssociate_Group,CreateCustomerCanvasTrial,AcquisitionsWF,BTVolumeSalesAgent,BB_HotSite_Trial,BTPANWiFiAgent,WaiveHubChargeGroup,BTBInboundRetentionAOTAgent,MultiportONT,BTSalesHubPage,Unbundle,BTSalesAppliGroup,BB_OptPSTNCeasewithFTTP_TrialGroup,DashboardAgent,BB_WaiveDowngradeChrgGroup,BB_WaiveHubDelChargeGroup,StandaloneBBCPE,VELHostApp,BB_SOGEA_Group,BB_CHOP3_Pro_TrialGroup,ULTRA_TrialGroup,BillingEnquiryWF,BTDIAgent,BT_SOGEALBW,BTBCOTextAOTAgent,360DegreeBetaHostApp,BTWiFiAgent,CVE_concurrent_ordering,BTCreateCustomer,MailboxManagementHostApp,FTTP_WLTO_TrialGroup,Force_Cancel,CloudVoiceBPHostApp,BTBL2CServiceRole,Division_Business,BPSSalesManagerAgent,AppDirectHostApp,GOC_RetrieveOrder,FL_ConversionToSogea,BTSPBEAgent,CV_Express_CiscoATA191,GOC_AmendCancel,BB_Firework_TrialGroup,BTBServicewf,BB_WaiveCeaseChrgGroup,BB_BTBSF_TrialGroup,BTWNonRegulatedProductAccess,AOContractDowngrade,CloudVoice_Complex_Test_Trials,AssetMergeforBundlingWF,BB_WaiveHubChargeGroup,PortNudgeToolHostApp,WriteAccessMCT,BTCInboundSaleswf,BTFraudwf,Reasset,CVTest,IssueMtMyDeskHostApp,MultiTaskAppligroup,BTFraudAgent,MarketoCampaignHostApp,BB_ReplaceBusHubGroup,EECC_Contract_Agent,T2R_CHOP3_Trial,BTGSContractAdminwf,360DegreeViewerHostApp,BTBPhonebookAgent,SalesWorkFlow,BB_CHOP3_Hyperfast_TrialGroup,addressSearch,Paps_Online_TrialGroup,BB_CoP_TrialGroup,EvsSalesForceHostApp,BTBServiceAgent_VAS_Sales_Service,CMP_Cmplnt,BB_CHOP2_TrialGroup,UKB_MVNO,Vel",
                    "AliasIDs": None,
                    "ChannelProfile": None,
                    "IsBackOffice": None,
                    "SalesEnquiryTelNo": None,
                    "DeliveryEnquiryTelNo": None,
                    "HasNCPService": False,
                    "TermsAndCondition": False,
                    "IsAgentOnline": False,
                    "IsCreditVetRequired": True,
                    "AdminCrmContactKey": None,
                    "AdminPinVerified": 0,
                    "UserRoleStatus": 0,
                    "clientCredentialStatusField": None,
                    "IsCUGAdministrator": False,
                    "UserfirstName": "",
                    "UserlastName": "",
                    "Usertitle": "",
                    "UseremailAddress": "",
                    "crmContactKey": "",
                    "cugId": "",
                    "OrgID": None,
                    "MasterContactId": None,
                    "TradingName": "",
                    "Action": "provide",
                    "ShadowContacts": None,
                    "BlockAgentEIN": None,
                    "BlockDate": None,
                    "ClientIdentityValueWithNoAlias": None,
                    "OUC": None,
                    "IsContactUpdateRequired": False,
                    "IsMarkedForDeletion": False,
                    "MailBoxDeletionDate": None,
                    "ReasonForDeletion": None,
                    "IsLoginDisabled": False,
                    "BTDealingChannel": None,
                    "IsProfileSuspended": False,
                    "IsAdminPinLocked": False,
                    "IsRegistrationPending": False,
                    "HasContextChanged": False,
                    "SourceSystem": None,
                    "IconRequestID": "0901e1c8-5381-4432-bd43-a7b795e89814",
                    "IconBacMatch": False,
                    "IconServiceIdScenarios": False,
                    "OrderBehalfOf": None,
                    "PostCode": None,
                    "IsProfileValidationPending": False,
                    "ProfileActivationCode": None,
                    "PrimayContactEmailAddress": None,
                    "ContentControlCFSId": None,
                    "SMSessionID": None,
                    "CUGList": None,
                    "CDEUserId": None,
                    "Category": "",
                    "UUID": None,
                    "BusinessAppStatus": None,
                    "BusinessAppLastLogin": None,
                    "BusinessAppVersion": None,
                    "BusinessAppOSVersion": None,
                    "AppDirectValidBacs": None,
                    "IsMerakiServiceAssociated": False,
                    "MerakiDescription": None,
                    "ClientCredentialType": None,
                    "SecretPin": None,
                    "IsSecretPinPresent": False,
                    "AggregatedCustomerType": None,
                    "ClientIdentityStatus": None,
                    "ProfileType": None
                },
                "JourneyData": {
                    "userProfResp": None,
                    "FTTCInstallLaunch": False,
                    "FulfillmentOrderNumber": "",
                    "Retrievable": "",
                    "ConfiguredDomainItems": None,
                    "JourneyUrl": None,
                    "ContractID": "",
                    "IsOneSiebelPlan": False,
                    "OpenOrderValidator": {
                        "modifyFlag": 0,
                        "orderkey": None,
                        "orderType": None,
                        "customerAgreedDate": None
                    },
                    "IsOptionCOn": False,
                    "ContactID": "",
                    "AoojRecordType": "",
                    "FudgeFactor": None,
                    "FlowType": "",
                    "OpenOrderCheck": True,
                    "ModifyUrl": "",
                    "Journey_Url": "/CreateCustomerV2/CreateCustomer?btbLegacy=N",
                    "MDMCustomerID": None,
                    "CustomerID": "",
                    "SessionID": None,
                    "BillingAccountKey": "",
                    "CustomerStatus": None,
                    "LeCode": None,
                    "LeId": "",
                    "AgentEIN": "920191895",
                    "IsCustomerStrategic": False,
                    "IsCreditVetRequired": False,
                    "ProvisionInstruction": "",
                    "OrderId": "",
                    "AssetId": "",
                    "ProductName": "",
                    "ProductCode": "",
                    "SAction": "provide",
                    "RequestId": "0901e1c8-5381-4432-bd43-a7b795e89814",
                    "RequestDateTime": "01/12/2023 10:06:53",
                    "AgentFirstName": "SOGEA EIN",
                    "AgentLastName": "shaik",
                    "AgentTelephoneNo": "+44 1442 296997",
                    "EmailId": "ayesha.shaik@bt.com",
                    "UserRole": "BDU",
                    "ChannelProfile": "CS Broadband COT",
                    "IsBackOffice": "Y",
                    "ReferenceOrderNo": None,
                    "OrderVersionNo": None,
                    "Channel": "Agent",
                    "InteractionType": "",
                    "InteractionId": "",
                    "ReferenceOderNo": "",
                    "WorkitemId": "",
                    "WorkitemDescription": "",
                    "Faultid": "",
                    "ThomasSkyEquipment": None,
                    "MsoRefID": "",
                    "Interactioncontactid": "",
                    "RequestType": "NCust",
                    "SalesEnquiryTelNo": "0800400400",
                    "AgentType": "",
                    "DeliveryEnquiryTelNo": "0800777666",
                    "BtDealingChannel": "CCC",
                    "OpportunityReferenceNo": "",
                    "ServiceID": "",
                    "SelectServiceID": None,
                    "SelectServicePointId": None,
                    "ServicePointId": "",
                    "ServiceAccountId": "",
                    "SiteId": "",
                    "NadKey": "",
                    "ProductInstanceId": "",
                    "ResellerId": "1",
                    "CrossSellerId": "",
                    "ThresholdValue": None,
                    "BtbLegacyFlag": "",
                    "NLTag": "",
                    "eBilling": "",
                    "DirectDebit": "",
                    "Title": "",
                    "ContactFirstName": "",
                    "ContactLastName": "",
                    "Owner": "",
                    "CugID": None,
                    "BillingAgentEIN": "",
                    "ContactIntegrationID": "",
                    "IsNewJourney": True,
                    "CDEAgentSearchType": "",
                    "CDEAgentSearchValue": "",
                    "customerJourneyData": {
                        "custDetail": None,
                        "leEntities": None,
                        "leDetails": None,
                        "address": None
                    },
                    "creditVet": {
                        "countOfCreditvetCalls": 0,
                        "lastTotalRiskValue": 0,
                        "readyForCreditCheck": False,
                        "firstProductConfiguredCreditCheckDone": False,
                        "isProceedToActivationCreditCheckDone": False,
                        "mcwVetKey": None
                    },
                    "IsAssociatedBPR": False,
                    "IsMovePageloadRequest": False,
                    "IsVASAdminAvailable": False,
                    "IsNewVASAdmin": False,
                    "IsVASAdminConfigured": False,
                    "IsVASCDEProfile": True,
                    "ServiceInstanceKey": None,
                    "ServiceCode": None,
                    "OpenZoneSiks": None,
                    "BasketdomainData": None,
                    "VASAdmindomainData": None,
                    "VASAdminExternalDom": None,
                    "ProductDefJson": None,
                    "ProductDependencyJson": None,
                    "IsFromCustomerZone": False,
                    "IsOpportunity": False,
                    "T2RFaultRefId": "",
                    "ReplacementAssetId": "",
                    "IsRetrievedOrder": False,
                    "SubStatus": "",
                    "ProjectRefId": "",
                    "BaseLeadDate": "",
                    "OrderCreationDate": "01/12/2023 10:06:53",
                    "IsAgentCreditVetSameEIN": False,
                    "ExistingWorkItemEIN": None,
                    "IsAgentCreditCallDone": False,
                    "RedirectToNewAmend": True,
                    "GroupOrderNumber": None,
                    "CanNavigateBack": True,
                    "IsLeadTimeCallMade": False,
                    "IsGocOCCopiedToBasket": False,
                    "IsCOTAgent": True,
                    "IsSalesAgent": True,
                    "IsDIAgent": True,
                    "IsFirstGOCOrder": None,
                    "OrderJourneyType": 1,
                    "OrderGUID": "b313815c-3410-4f29-9f6b-67c6f3c2965a",
                    "IsBundleProduct": False,
                    "IsNewCease": False,
                    "RedirectToBundleConversion": False,
                    "ConvertToBundleSCode": None,
                    "BundleAssetId": None,
                    "IsLegacyVasAdmin": False,
                    "IsnewBBPage": False,
                    "AgentDN": "",
                    "CreateLECTP": False,
                    "AccountManagerEIN": None,
                    "VATEvidence": None,
                    "ShouldVisitVATValidationPage": False,
                    "IsCloudVoiceJourney": False,
                    "IsISDNModifyV2": False,
                    "IsCreateOrderExecuted": False,
                    "IsDIJourney": False,
                    "JourneyLineItemData": None,
                    "PlanType": "",
                    "IsDirAgent": True,
                    "CeaseUrl": "",
                    "IsNetworkModify": False,
                    "IsValidateRetrieveBasketDone": False,
                    "IsMobilityModify": False,
                    "IsBusinessAppsActivated": False,
                    "ProductGroupName": None,
                    "ReturnToIncidentRequired": None,
                    "UserProfile": None,
                    "IsBbLinked_Sogea": False,
                    "BbAssetId_Sogea": None,
                    "GroupOrderStatus": None,
                    "GroupOrderSubStatus": None,
                    "SiteContactVisitedModify": False,
                    "IsThirdParty": None,
                    "IsSogeaToWlrConversion": False,
                    "ValidationLevel": "",
                    "IsEscalatePreponeLaunch": False,
                    "IsServiceManagerAgent": True,
                    "IsAllModifyConfigurationDone": False,
                    "IsAllModifyBillingDone": False,
                    "IsLowtoHighBundleCompConversion": False,
                    "IsFLNetworkModify": False,
                    "IncompleteConvert": False,
                    "IsCarryOverSelectedForBundle": None,
                    "IsOfferApplicable": False,
                    "IsNewOD": False,
                    "HubAssetId": None,
                    "NCallId": "",
                    "BundleContractTermsInfo": [],
                    "IsBTSportRVChangeAgent": False,
                    "IsLikeToLikeBudnleMove": False,
                    "IsOverlapBundleMove": False,
                    "FTTPInstallLaunch": False,
                    "IsStandAlone4GAssureJourney": False,
                    "TargetBundleInstallationXmlRef": None,
                    "IsESWithFTTPNewONT": False,
                    "IsFTTPWithNewONT": False,
                    "LeName": "",
                    "BBToSogeaConversion": False,
                    "AccessLineId": None,
                    "RMAuthorisation": None,
                    "ReplacementreasonCode": None,
                    "ExpertSupportCharge": "",
                    "NumberOfWiFiDisksAsseted": "",
                    "IsAddressUpdated": False,
                    "ReplaceXMLRef": None,
                    "SATToolDetails": None,
                    "IsESRebookAppointmentWarning": False,
                    "NoOfDiscsRequestedForReplacement": "",
                    "RecommendedDetails": None,
                    "CeaseWithRefund": "",
                    "RedirectToNewVasBillingPage": False,
                    "IsWLRWithdrawnAddress": False,
                    "IsNumberTransferOnPC": False,
                    "NumberTransferedOnPC": None,
                    "ParentCWDAssetId": None,
                    "IsSogeaToFTTPConversion": False,
                    "EnableAssociatedOrderingKCIs": None,
                    "CeaseAssetIdFromT2R": None,
                    "PEGAToolDetails": None,
                    "RedirectToBundleBuilderPage": False,
                    "IsRecommendationValidationDone": False,
                    "IsBTWiFiManagerAgent": False,
                    "IsFttpWinBackFromSogea": False,
                    "IsPSTNToSogeaConversion": False,
                    "IsNTTPTerminationType": False,
                    "FieldSupplier": None,
                    "SFSAppointmentFields": None,
                    "IsBTPANWiFiManagerAgent": False,
                    "IsBTSportTrialGroupManager": False,
                    "DocumentID": "",
                    "SelectedORAddress": None,
                    "SelectedSogeaLineProductType": None,
                    "SkipForFirstOrder": None,
                    "WLRWithdrawlForFTTPPriorityExchangeScenarioInfo": [],
                    "IsSolusBundleConversion": False,
                    "SolusBundleRetainProductPrice": None,
                    "SogeaNonServedPremises": False,
                    "IsExpertSetupOpen": None,
                    "ExpertSetupOrder": None,
                    "DirectoryNumber": None,
                    "BB1PFMJourney": False,
                    "OldAccessTechnology": None
                },
                "Basket": None,
                "LegalEntityResponse": None,
                "ContactDetails": None,
                "SelectedOrganizationName": None,
                "SelectedOrganizationSacCode": None,
                "IsAdditionalContactChecked": False,
                "OrganizationList": None,
                "ModifyType": None,
                "AccountStatus": None,
                "SelectedCustomerRegion": 0,
                "IsCustomerIdentificationScenario": False,
                "IsFromICON": False,
                "IconCreateCustomerSuccessURL": "https://moda.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?2FDF57A3CBC238FA5C9EC3E6DB44E1B0",
                "IconCreateCustomerFailureURL": "https://moda.btbusinesspartnersales.bt.com/partner_portal/Pol_pp_UKB_Cust_Details.aspx?326FA0E0B5195C775C9EC3E6DB44E1B0",
                "HelpDeskIdentifier": "HELPDESK_PORTAL",
                "EUTaxExemptRefNumber": None,
                "IsEUCountrySelected": False,
                "CUGDetails": None,
                "ContactsList": None,
                "IsModelFromSession": False,
                "ChannelName": "Agent",
                "IsCustomerBaseAgent": False,
                "FlagIsStrategicJourneyAllowed": "ON",
                "IsIncorporated": False,
                "IsContactGenericConsent": True,
                "IsConsentRequired": True,
                "RequestMode": None,
                "IsDirectMode": False,
                "ExternalSystem": None,
                "RedirectUrl": None
            }, */
            payload: payload,
            headers: {
                "Accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": "Bearer " + jira_api_key,
            },
            failOnStatusCode: true
            //verify: 'Fales'
        })
    })
})